using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
namespace MyGM.Companion;
public sealed record AutomationStep(string Name,MyGmScreen Expected,MyGmScreen Target,string[] Keys,string CaptureAs);
public sealed record AutomationProfile(string Language,string AspectRatio,AutomationStep[] Steps);
public sealed record AutoGmProgress(int Current,int Total,string Title,string Detail,string Tone);
public sealed record AutoGmResult(CareerProfile Profile,ShowRecommendation Recommendation,MyGmScreen[] Screens,string[] Warnings);
public sealed class AutoGmOrchestrator {
 readonly WindowCaptureService capture;readonly OcrProcessService ocr;readonly RosterCardScannerAdapter roster;readonly KeyboardAutomationService keyboard=new();readonly string root,dataDir,cacheDir;
 public event Action<AutoGmProgress>? Progress;
 public AutoGmOrchestrator(WindowCaptureService capture,OcrProcessService ocr,string root,string dataDir,string cacheDir){this.capture=capture;this.ocr=ocr;this.root=root;this.dataDir=dataDir;this.cacheDir=cacheDir;roster=new(ocr);}
 public async Task<AutoGmResult> RunAsync(CancellationToken token){var profile=CareerProfileService.LoadActive(dataDir)??CareerProfileService.CurrentEcwCalibration() with{Id="career-auto-"+DateTime.Now.ToString("yyyyMMdd-HHmmss"),Name="Automatisch erkannter Spielstand",Week=1,RosterRows=[]};var window=await capture.FindWweWindowAsync(token).WaitAsync(TimeSpan.FromSeconds(5),token)??throw new InvalidOperationException("WWE 2K26 wurde nicht gefunden.");var automation=LoadProfile();var seen=new List<MyGmScreen>();var raw=new Dictionary<string,string>();var warnings=new List<string>();var current=await ReadAsync(window,"start",token);Progress?.Invoke(new(0,automation.Steps.Length,"WWE 2K26 erkannt",$"{window.Mode} · Bildschirm: {current.Screen}","good"));for(var escape=0;current.Screen!=MyGmScreen.Home&&escape<4;escape++){Progress?.Invoke(new(0,automation.Steps.Length,"Startseite wird gesucht","Sicherer ESC-Schritt mit anschließender Kontrolle","neutral"));await keyboard.SendAsync(window,["ESCAPE"],token);current=await ReadAsync(window,$"home-{escape}",token);}if(current.Screen!=MyGmScreen.Home)throw new InvalidOperationException("AUTOMATIK GESTOPPT: MyGM-Startseite wurde nicht sicher erkannt. Bitte einmal die Startseite öffnen und erneut starten.");raw["Home"]=current.Text;seen.Add(current.Screen);var detected=ParseHome(current.Text,profile);profile=profile with{Brand=detected.Brand,Week=detected.Week,UpdatedAt=DateTimeOffset.Now};for(var i=0;i<automation.Steps.Length;i++){var step=automation.Steps[i];token.ThrowIfCancellationRequested();if(current.Screen!=step.Expected)throw new InvalidOperationException($"AUTOMATIK GESTOPPT: Vor '{step.Name}' wurde {step.Expected} erwartet, erkannt wurde {current.Screen}.");Progress?.Invoke(new(i+1,automation.Steps.Length,step.Name,$"{step.Expected} → {step.Target}","neutral"));await keyboard.SendAsync(window,step.Keys,token);current=await ReadAsync(window,step.Name,token);if(current.Screen!=step.Target)throw new InvalidOperationException($"AUTOMATIK GESTOPPT: Nach '{step.Name}' wurde {step.Target} nicht eindeutig erkannt ({current.Screen}). Es wurde nichts weiter bedient.");seen.Add(current.Screen);raw[step.CaptureAs]=current.Text;if(current.Screen==MyGmScreen.Roster){try{var profileDir=Path.Combine(CareerProfileService.ProfilesDirectory(dataDir),profile.Id);var scan=await roster.ScanAsync(current.Path,profileDir,token,p=>Progress?.Invoke(new(i+1,automation.Steps.Length,"Roster wird gelesen",p,"neutral")));if(scan.Rows.Length>=4)profile=profile with{RosterRows=scan.Rows,RosterCaptureHash=scan.SourceHash,UpdatedAt=DateTimeOffset.Now};else warnings.Add("Roster-Karten konnten nicht vollständig gelesen werden; letzter sicherer Roster bleibt aktiv.");}catch(Exception ex){warnings.Add("Roster-Scan: "+ex.Message);}}
 }
 if(profile.RosterRows.Length<4)throw new InvalidOperationException("AUTOMATIK GESTOPPT: Kein sicherer Roster vorhanden.");var slots=ParseSlots(raw.GetValueOrDefault("Booking",""),profile);profile=profile with{MatchSlots=slots.Matches,PromoSlots=slots.Promos,UpdatedAt=DateTimeOffset.Now};CareerProfileService.SaveActive(dataDir,profile);File.WriteAllText(Path.Combine(dataDir,"roster.json"),JsonSerializer.Serialize(new RosterSnapshot(profile.Brand,profile.Week,profile.RosterRows,DateTimeOffset.Now),Options()));var objectiveList=ObjectiveParser.Parse(raw.GetValueOrDefault("Protocol","")+Environment.NewLine+raw.GetValueOrDefault("Home",""),profile.Week).Select(x=>x.ToEditorLine()).ToList();var eventContext=MyGmEventParser.Parse(raw.GetValueOrDefault("Career",""),profile.Week);if(eventContext is not null){warnings.Add($"Event erkannt: {eventContext.Name}. {eventContext.PlanningNote}");if(eventContext.Week is null||eventContext.Week==profile.Week)objectiveList.Add($"Event | Allgemein | {eventContext.Name}: {eventContext.PlanningNote} | {eventContext.Week?.ToString()??"–"} | Hoch | Offen");var dir=Path.Combine(CareerProfileService.ProfilesDirectory(dataDir),profile.Id);var metadata=CareerIntelligenceEngine.LoadMetadata(dir,profile) with{NextPleWeek=eventContext.Week};CareerIntelligenceEngine.SaveMetadata(dir,metadata);}var parsed=objectiveList.Distinct(StringComparer.OrdinalIgnoreCase).ToArray();File.WriteAllText(Path.Combine(dataDir,"objectives.json"),JsonSerializer.Serialize(new ObjectivesSnapshot(raw.GetValueOrDefault("Protocol",""),parsed,DateTimeOffset.Now),Options()));var savedBudget=File.Exists(Path.Combine(dataDir,"show-plan.json"))?JsonSerializer.Deserialize<ShowPlan>(File.ReadAllText(Path.Combine(dataDir,"show-plan.json")),Options())?.Budget:0;var budget=ParseMoney(raw.GetValueOrDefault("Home",""))??savedBudget??0;var learning=LearningEngine.LoadProfile(Path.Combine(dataDir,"learning-profile.json"));var plan=PlannerEngine.Generate(profile.RosterRows,parsed,budget,learning,profile.MatchSlots,profile.PromoSlots);warnings.AddRange(plan.Warnings);File.WriteAllText(Path.Combine(dataDir,"show-plan.json"),JsonSerializer.Serialize(new ShowPlan($"Woche {profile.Week}",budget,parsed.FirstOrDefault()??"",$"Automatisch · {profile.Name}",plan.Render(),DateTimeOffset.Now),Options()));Progress?.Invoke(new(automation.Steps.Length,automation.Steps.Length,"Show fertig berechnet",$"{plan.Matches.Count} Matches · {plan.Promos.Count} Promos","good"));return new(profile,plan,seen.ToArray(),warnings.Distinct().ToArray());}
 async Task<(MyGmScreen Screen,string Text,string Path)> ReadAsync(WindowInfo window,string name,CancellationToken token){var shot=await capture.CaptureAsync(window,cacheDir,token);var result=await ocr.RecognizeAsync(shot.SavedPath,token);if(!result.Ok)throw new InvalidOperationException(result.Error??"Bildschirm konnte nicht gelesen werden.");return(MyGmScreenClassifier.Classify(result.Text),result.Text,shot.SavedPath);}
 AutomationProfile LoadProfile(){var path=Path.Combine(root,"config","autogm-navigation.de-DE.json");if(File.Exists(path)){try{return JsonSerializer.Deserialize<AutomationProfile>(File.ReadAllText(path),Options())??DefaultProfile();}catch{}}return DefaultProfile();}
 static AutomationProfile DefaultProfile()=>new("de-DE","16:9",[new("Roster öffnen",MyGmScreen.Home,MyGmScreen.Roster,["PAGEDOWN","PAGEDOWN","PAGEDOWN"],"Roster"),new("Zur Startseite",MyGmScreen.Roster,MyGmScreen.Home,["PAGEUP","PAGEUP","PAGEUP"],"Home"),new("Protokoll und Versprechen öffnen",MyGmScreen.Home,MyGmScreen.Protocol,["F1"],"Protocol"),new("Protokoll schließen",MyGmScreen.Protocol,MyGmScreen.Home,["ESCAPE"],"Home"),new("Show-Buchung erkennen",MyGmScreen.Home,MyGmScreen.Booking,["PAGEDOWN"],"Booking"),new("Zur Startseite zurück",MyGmScreen.Booking,MyGmScreen.Home,["PAGEUP"],"Home"),new("Karriere und Events erkennen",MyGmScreen.Home,MyGmScreen.Career,["PAGEUP"],"Career"),new("Automatik abschließen",MyGmScreen.Career,MyGmScreen.Home,["PAGEDOWN"],"Home")]);
 static (string Brand,int Week) ParseHome(string text,CareerProfile old){var week=Regex.Match(text,@"SHOW\s*(\d+)",RegexOptions.IgnoreCase);var brand=new[]{"ECW","RAW","SMACKDOWN","NXT","WCW"}.FirstOrDefault(x=>text.Contains(x,StringComparison.OrdinalIgnoreCase))??old.Brand;return(brand,week.Success&&int.TryParse(week.Groups[1].Value,out var w)?w:old.Week);}
 static decimal? ParseMoney(string text){var match=Regex.Match(text,@"BUDGET\s*[:.]?\s*([0-9.,]+)",RegexOptions.IgnoreCase);if(!match.Success)return null;var digits=new string(match.Groups[1].Value.Where(char.IsDigit).ToArray());return decimal.TryParse(digits,out var value)?value:null;}
 static (int Matches,int Promos) ParseSlots(string text,CareerProfile old){var midcards=Regex.Matches(text,"MIDCARD",RegexOptions.IgnoreCase).Count;var matches=midcards is >=1 and <=6?midcards+2:old.MatchSlots;var empty=Regex.Matches(text,"UNGEBUCHT|UNGBUCHT",RegexOptions.IgnoreCase).Count;var promos=empty>matches&&empty-matches<=8?empty-matches:old.PromoSlots;return(Math.Clamp(matches,2,8),Math.Clamp(promos,0,8));}
 static JsonSerializerOptions Options(){var options=new JsonSerializerOptions{PropertyNameCaseInsensitive=true,WriteIndented=true};options.Converters.Add(new JsonStringEnumConverter());return options;}
 sealed class RosterCardScannerAdapter {readonly OcrProcessService ocr;public RosterCardScannerAdapter(OcrProcessService ocr)=>this.ocr=ocr;public async Task<RosterScanResult> ScanAsync(string path,string dir,CancellationToken token,Action<string> progress)=>await RosterCardScanner.ScanAsync(path,dir,ocr,(done,total)=>progress($"{done}/{total} Karten"),token);}
}
