using System.Text.Json;
using System.Text.RegularExpressions;
using System.IO;
namespace MyGM.Companion;
public sealed record CareerMetadata(Dictionary<string,int> InjuryWeeks,Dictionary<string,int> ContractWeeks,int? NextPleWeek,long? Fans,decimal? Budget,List<BusinessSnapshot> Business,List<FreeAgentCandidate> FreeAgents){public static CareerMetadata Empty()=>new(new(StringComparer.OrdinalIgnoreCase),new(StringComparer.OrdinalIgnoreCase),null,null,null,[],[]);}
public sealed record BusinessSnapshot(int Week,decimal Budget,long Fans,decimal Revenue,decimal ShowCost);
public sealed record FreeAgentCandidate(string Name,string Gender,string Role,string Style,int Popularity,int Stamina,decimal Cost);
public sealed record CareerNotice(string Group,string Title,string Detail,string Tone);
public sealed record SuperstarCareerCard(string Name,string Style,int Popularity,int Stamina,string Manager,int Rivalry,string Status,string Form,string History,string? ImagePath);
public sealed record CareerReport(IReadOnlyList<CareerNotice> Notices,IReadOnlyList<SuperstarCareerCard> Superstars,string Summary);
public static class CareerIntelligenceEngine {
 static readonly JsonSerializerOptions JsonOptions=new(){WriteIndented=true,PropertyNameCaseInsensitive=true};
 public static CareerMetadata LoadMetadata(string dir,CareerProfile p){var path=Path.Combine(dir,"career-intelligence.json");try{if(File.Exists(path))return JsonSerializer.Deserialize<CareerMetadata>(File.ReadAllText(path),JsonOptions)??CareerMetadata.Empty();}catch{}var m=CareerMetadata.Empty();if(p.Id=="ecw-s1")m=m with{InjuryWeeks=new(StringComparer.OrdinalIgnoreCase){{"Kevin Owens",12},{"Cody Rhodes",2},{"Roman Reigns",2},{"Finn Bálor",4},{"Omos",4}},Budget=1_042_425,Fans=1_578_702};Directory.CreateDirectory(dir);File.WriteAllText(path,JsonSerializer.Serialize(m,JsonOptions));return m;}
 public static CareerReport Build(CareerProfile p,CareerMetadata m,IReadOnlyList<ShowOutcome> history,string[] objectives,string? plan,string dir){PlannerEngine.TryParseRoster(p.RosterRows,out var stars,out _);var n=new List<CareerNotice>();Injuries(p,m,stars,n);Rivalries(p,m,stars,n);Promises(p,objectives,n);Business(m,n);Ple(p,m,n);Contracts(m,stars,n);Agents(m,stars,n);Repeats(history,n);Managers(stars,n);Accuracy(history,plan,n);var images=Images(dir);var cards=stars.OrderByDescending(x=>x.Popularity).Select(s=>Card(s,m,history,images)).ToArray();return new(n,cards,$"{p.Name} · Woche {p.Week} · {n.Count(x=>x.Tone=="danger")} dringende Hinweise · {history.Count} gelernte Shows");}
 static void Injuries(CareerProfile p,CareerMetadata m,List<Superstar> s,List<CareerNotice> n){foreach(var x in s.Where(x=>m.InjuryWeeks.ContainsKey(x.Name)||x.Stamina==0)){var w=m.InjuryWeeks.GetValueOrDefault(x.Name);n.Add(new("VERLETZUNG",x.Name,w>0?$"Noch {w} Woche(n) verletzt · frühestens Woche {p.Week+w} wieder einplanen.":"Verletzt erkannt · Dauer noch nicht sicher erfasst.","danger"));}foreach(var x in s.Where(x=>x.Stamina>0).OrderBy(x=>x.Stamina).Take(5))n.Add(new("AUSDAUER",x.Name,$"Aktuell {x.Stamina} · bei Schonung: {Math.Min(100,x.Stamina+12)} / {Math.Min(100,x.Stamina+24)} / {Math.Min(100,x.Stamina+36)} in den nächsten Wochen.",x.Stamina<35?"warning":"neutral"));}
 static void Rivalries(CareerProfile p,CareerMetadata m,List<Superstar> s,List<CareerNotice> n){foreach(var x in s.Where(x=>x.Rivalry>0).OrderByDescending(x=>x.Rivalry)){var end=x.Rivalry>=3?(m.NextPleWeek is int ple?$"Abschluss in Woche {ple} beim PLE empfohlen.":"Abschluss beim nächsten PLE empfohlen; PLE-Woche noch nicht erfasst."):"Weiter aufbauen, noch nicht abschließen.";n.Add(new("RIVALITÄT",x.Name,$"Stufe {x.Rivalry}/4 · {end}",x.Rivalry>=4?"warning":"neutral"));}}
 static void Promises(CareerProfile p,string[] rows,List<CareerNotice> n){if(rows.Length==0){n.Add(new("ZIELE","Noch keine bestätigten Ziele","Zielseite gezielt scannen, damit erfüllte, gefährdete und gescheiterte Versprechen verfolgt werden.","missing"));return;}foreach(var row in rows){var x=row.Split('|',StringSplitOptions.TrimEntries);if(x.Length<3)continue;var d=x.Length>3&&int.TryParse(x[3],out var deadline)?deadline:0;var status=x.Length>5?x[5]:"Offen";var overdue=status.Equals("Offen",StringComparison.OrdinalIgnoreCase)&&d>0&&d<p.Week;n.Add(new("ZIEL / VERSPRECHEN",x[2],$"{(x.Length>1?x[1]:"Allgemein")} · Deadline {(d>0?$"Woche {d}":"nicht erkannt")} · {(overdue?"GESCHEITERT / ÜBERFÄLLIG":status.ToUpperInvariant())}",overdue||status.Contains("Gescheit",StringComparison.OrdinalIgnoreCase)?"danger":status.Contains("Erfüllt",StringComparison.OrdinalIgnoreCase)?"good":"warning"));}}
 static void Business(CareerMetadata m,List<CareerNotice> n){if(m.Business.Count>=2){var a=m.Business.OrderBy(x=>x.Week).TakeLast(2).ToArray();var profit=a[1].Revenue-a[1].ShowCost;n.Add(new("FINANZEN",$"Woche {a[1].Week}: {(profit>=0?"Gewinn":"Verlust")} {profit:N0} $",$"Budget Δ {a[1].Budget-a[0].Budget:+0;-0;0} $ · Fans Δ {a[1].Fans-a[0].Fans:+0;-0;0}",profit<0?"warning":"good"));}else n.Add(new("FINANZEN",$"Budget {(m.Budget is decimal b?$"{b:N0} $":"nicht erfasst")} · Fans {(m.Fans is long f?$"{f:N0}":"nicht erfasst")}","Für Einnahmen- und Fantrend werden mindestens zwei Ergebnisbildschirme benötigt.","missing"));}
 static void Ple(CareerProfile p,CareerMetadata m,List<CareerNotice> n){if(m.NextPleWeek is not int ple||ple<=p.Week){n.Add(new("MEHRWOCHENPLAN","Nächster PLE noch nicht erkannt","PLE-Übersicht gezielt erfassen; bis dahin plant der Companion nur die aktuelle Woche sicher.","missing"));return;}for(var w=p.Week;w<=ple;w++){var left=ple-w;var task=left==0?"Rivalitäten abschließen, höchste POP und Spezialmatches einsetzen":left==1?"Stars schonen, Abschlussgegner festlegen, Budget sichern":left<=3?"Rivalitäten auf Stufe 3–4 bringen":"Ausdauer und Popularität aufbauen";n.Add(new("BIS ZUM PLE",$"Woche {w}",task,w==ple?"good":"neutral"));}}
 static void Contracts(CareerMetadata m,List<Superstar> s,List<CareerNotice> n){if(m.ContractWeeks.Count==0){n.Add(new("VERTRÄGE","Vertragslaufzeiten noch nicht erfasst","Roster-Verwaltung gezielt scannen; danach warnen wir 3 Wochen vor Ablauf.","missing"));return;}foreach(var x in s.Where(x=>m.ContractWeeks.ContainsKey(x.Name)).OrderBy(x=>m.ContractWeeks[x.Name])){var w=m.ContractWeeks[x.Name];n.Add(new("VERTRAG",x.Name,$"Noch {w} Woche(n) · {(w<=3?"jetzt verlängern":"keine sofortige Aktion")}",w<=3?"danger":"neutral"));}}
 static void Agents(CareerMetadata m,List<Superstar> s,List<CareerNotice> n){var styles=new[]{"Fighter","Bruiser","Cruiser","Giant","Specialist"};var missing=styles.Where(style=>s.Count(x=>x.Style==style)<2).ToArray();if(m.FreeAgents.Count==0){n.Add(new("FREE AGENTS","Bedarf: "+(missing.Length==0?"Roster ausgeglichen":string.Join(", ",missing)),"Free-Agent-Seite noch nicht erfasst; keine Namen oder Preise werden erfunden.","missing"));return;}foreach(var f in m.FreeAgents.Where(x=>missing.Contains(x.Style)).OrderByDescending(x=>x.Popularity+x.Stamina/2).Take(4))n.Add(new("FREE-AGENT-TIPP",f.Name,$"{f.Style} · POP {f.Popularity} · Ausdauer {f.Stamina} · {f.Cost:N0} $ · schließt Klassenlücke.","good"));}
 static void Repeats(IReadOnlyList<ShowOutcome> h,List<CareerNotice> n){foreach(var g in h.OrderByDescending(x=>x.Week).Take(5).SelectMany(x=>x.Matches).GroupBy(x=>LearningProfile.PairKey(x.A,x.B)).Where(x=>x.Count()>=2))n.Add(new("WIEDERHOLUNG",g.Key.Replace("::"," vs "),$"In den letzten Shows {g.Count()}× gebucht · vorerst pausieren, außer eine Rivalität rechtfertigt es.","warning"));}
 static void Managers(List<Superstar> s,List<CareerNotice> n){foreach(var x in s.Where(x=>!string.IsNullOrWhiteSpace(x.Manager)))n.Add(new("MANAGER",x.Name,$"{x.Manager} beibehalten · vorhandene Zuordnung wird bei Card-Empfehlungen berücksichtigt.","neutral"));if(!s.Any(x=>!string.IsNullOrWhiteSpace(x.Manager)))n.Add(new("MANAGER","Keine sicheren Zuordnungen erkannt","Manager-Seite scannen; Empfehlungen werden erst aus echten Zuordnungen erstellt.","missing"));}
 static void Accuracy(IReadOnlyList<ShowOutcome> h,string? plan,List<CareerNotice> n){if(h.Count==0||string.IsNullOrWhiteSpace(plan)){n.Add(new("PROGNOSE-CHECK","Noch kein vollständiger Vergleich","Gespeicherten Auto-Plan und danach den Ergebnisbildschirm erfassen.","missing"));return;}var predicted=Regex.Matches(plan,@"Erwartung:\s*([0-9,.]+)[–-]([0-9,.]+)").Select(x=>(Num(x.Groups[1].Value)+Num(x.Groups[2].Value))/2).ToArray();var actual=h.OrderByDescending(x=>x.Week).First().Matches.Select(x=>x.Stars).ToArray();if(predicted.Length==0||actual.Length==0){n.Add(new("PROGNOSE-CHECK","Vergleich nicht möglich","Im gespeicherten Plan oder Ergebnis fehlen Sternwerte.","missing"));return;}var count=Math.Min(predicted.Length,actual.Length);var delta=Enumerable.Range(0,count).Average(i=>actual[i]-predicted[i]);n.Add(new("PROGNOSE-CHECK",$"Geplant vs. tatsächlich: Δ {delta:+0.0;-0.0;0.0} ★",$"{count} Matches · Prognose Ø {predicted.Take(count).Average():0.0} · Ergebnis Ø {actual.Take(count).Average():0.0}.",Math.Abs(delta)>.75?"warning":"good"));}
 static SuperstarCareerCard Card(Superstar s,CareerMetadata m,IReadOnlyList<ShowOutcome> h,Dictionary<string,string> images){var ms=h.SelectMany(x=>x.Matches.Select(y=>(show:x,match:y))).Where(x=>x.match.A.Equals(s.Name,StringComparison.OrdinalIgnoreCase)||x.match.B.Equals(s.Name,StringComparison.OrdinalIgnoreCase)).OrderBy(x=>x.show.Week).ToArray();var form=ms.Length==0?"Noch keine Matchdaten":$"Ø {ms.Average(x=>x.match.Stars):0.0} ★ · letzte {string.Join(" / ",ms.TakeLast(3).Select(x=>$"{x.match.Stars:0.0}★"))}";var hist=ms.Length==0?"Keine Historie":string.Join(" · ",ms.TakeLast(3).Select(x=>$"W{x.show.Week} {(x.match.A.Equals(s.Name,StringComparison.OrdinalIgnoreCase)?x.match.B:x.match.A)} ({x.match.MatchType})"));var status=m.InjuryWeeks.TryGetValue(s.Name,out var injury)?$"Verletzt · {injury} W.":s.Stamina==0?"Verletzt":"Einsatzbereit";if(m.ContractWeeks.TryGetValue(s.Name,out var contract))status+=$" · Vertrag {contract} W.";return new(s.Name,s.Style,s.Popularity,s.Stamina,s.Manager,s.Rivalry,status,form,hist,images.GetValueOrDefault(s.Name));}
 static Dictionary<string,string> Images(string dir){var r=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);try{var path=Path.Combine(dir,"last-roster-scan.json");if(!File.Exists(path))return r;using var doc=JsonDocument.Parse(File.ReadAllText(path));if(!doc.RootElement.TryGetProperty("Cards",out var cards)&&!doc.RootElement.TryGetProperty("cards",out cards))return r;foreach(var c in cards.EnumerateArray()){var row=Get(c,"RosterRow")??Get(c,"rosterRow");var image=Get(c,"ImagePath")??Get(c,"imagePath");if(row is not null&&image is not null)r[row.Split('|')[0].Trim()]=image;}}catch{}return r;}
 static string? Get(JsonElement e,string name)=>e.TryGetProperty(name,out var x)?x.GetString():null;
 static double Num(string s)=>double.TryParse(s.Replace(',','.'),System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out var v)?v:0;
}
