using System.Text.Json;
using System.IO;
namespace MyGM.Companion;
public sealed record MatchOutcome(string A,string B,string MatchType,double Stars);
public sealed record PromoOutcome(string Star,string PromoType,double Score);
public sealed record ShowOutcome(int Week,MatchOutcome[] Matches,PromoOutcome[] Promos,double EndRating,string Notes,DateTimeOffset SavedAt);
public sealed record LearnedMetric(int Samples,double Average){public LearnedMetric Add(double value)=>(new(Samples+1,(Average*Samples+value)/(Samples+1)));}
public sealed record LearningProfile(Dictionary<string,LearnedMetric> Pairings,Dictionary<string,LearnedMetric> MatchTypes,Dictionary<string,LearnedMetric> Superstars,Dictionary<string,LearnedMetric> Promos,int Shows,double AverageEndRating){
 public static LearningProfile Empty()=>new(new(StringComparer.OrdinalIgnoreCase),new(StringComparer.OrdinalIgnoreCase),new(StringComparer.OrdinalIgnoreCase),new(StringComparer.OrdinalIgnoreCase),0,0);
 public double MatchBonus(string a,string b,string type){var bonus=0d;if(Pairings.TryGetValue(PairKey(a,b),out var pair)&&pair.Samples>0)bonus+=(pair.Average-3)*7;if(MatchTypes.TryGetValue(type,out var mt)&&mt.Samples>1)bonus+=(mt.Average-3)*3;foreach(var name in new[]{a,b})if(Superstars.TryGetValue(name,out var star)&&star.Samples>1)bonus+=(star.Average-3)*1.5;return Math.Clamp(bonus,-12,16);}
 public static string PairKey(string a,string b)=>string.Compare(a,b,StringComparison.OrdinalIgnoreCase)<=0?$"{a}::{b}":$"{b}::{a}";
}
public sealed record LearningReport(LearningProfile Profile,string Summary,string[] Strengths,string[] Improvements);
public static class LearningEngine {
 public static ShowOutcome Parse(int week,string matchLines,string promoLines,double endRating,string notes){var matches=new List<MatchOutcome>();var line=0;foreach(var row in Lines(matchLines)){line++;var p=row.Split('|',StringSplitOptions.TrimEntries);if(p.Length<3)throw new FormatException($"Matchzeile {line}: Format 'A vs B | Matchtyp | Sterne' erwartet.");var names=p[0].Split(" vs ",2,StringSplitOptions.TrimEntries|StringSplitOptions.RemoveEmptyEntries);if(names.Length!=2)throw new FormatException($"Matchzeile {line}: 'vs' zwischen beiden Namen fehlt.");if(!double.TryParse(p[2].Replace(',', '.'),System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out var stars)||stars is <0 or >5)throw new FormatException($"Matchzeile {line}: Sterne müssen zwischen 0 und 5 liegen.");matches.Add(new(names[0],names[1],p[1],stars));}var promos=new List<PromoOutcome>();line=0;foreach(var row in Lines(promoLines)){line++;var p=row.Split('|',StringSplitOptions.TrimEntries);if(p.Length<3)throw new FormatException($"Promozeile {line}: Format 'Name | Promotyp | Wert 0–5' erwartet.");if(!double.TryParse(p[2].Replace(',', '.'),System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out var score)||score is <0 or >5)throw new FormatException($"Promozeile {line}: Wert muss zwischen 0 und 5 liegen.");promos.Add(new(p[0],p[1],score));}if(matches.Count==0)throw new InvalidOperationException("Mindestens ein Matchergebnis wird benötigt.");return new(week,matches.ToArray(),promos.ToArray(),Math.Clamp(endRating,0,5),notes,DateTimeOffset.Now);}
 public static LearningReport Learn(IReadOnlyList<ShowOutcome> history){var profile=LearningProfile.Empty();foreach(var show in history){foreach(var m in show.Matches){Add(profile.Pairings,LearningProfile.PairKey(m.A,m.B),m.Stars);Add(profile.MatchTypes,m.MatchType,m.Stars);Add(profile.Superstars,m.A,m.Stars);Add(profile.Superstars,m.B,m.Stars);}foreach(var p in show.Promos)Add(profile.Promos,$"{p.Star}::{p.PromoType}",p.Score);}var avgEnd=history.Count==0?0:history.Average(x=>x.EndRating);profile=profile with{Shows=history.Count,AverageEndRating=avgEnd};var strong=profile.Pairings.Where(x=>x.Value.Samples>=1&&x.Value.Average>=4).OrderByDescending(x=>x.Value.Average).Take(4).Select(x=>$"{x.Key.Replace("::"," vs ")}: Ø {x.Value.Average:0.0} ★ ({x.Value.Samples}×)").Concat(profile.MatchTypes.Where(x=>x.Value.Samples>=2&&x.Value.Average>=4).OrderByDescending(x=>x.Value.Average).Take(2).Select(x=>$"Matchtyp {x.Key}: Ø {x.Value.Average:0.0} ★")).ToArray();var weak=profile.Pairings.Where(x=>x.Value.Samples>=1&&x.Value.Average<3).OrderBy(x=>x.Value.Average).Take(4).Select(x=>$"{x.Key.Replace("::"," vs ")}: nur Ø {x.Value.Average:0.0} ★ – vorerst vermeiden").Concat(profile.MatchTypes.Where(x=>x.Value.Samples>=2&&x.Value.Average<3).OrderBy(x=>x.Value.Average).Take(2).Select(x=>$"Matchtyp {x.Key}: nur Ø {x.Value.Average:0.0} ★")).ToArray();var summary=$"LERNPROFIL · {history.Count} Shows · Endwertung Ø {avgEnd:0.0}/5 · {profile.Pairings.Count} Paarungen";return new(profile,summary,strong.Length==0?["Noch keine belastbare Stärke – weitere Shows erfassen."]:strong,weak.Length==0?["Noch kein wiederkehrendes Problem erkannt."]:weak);}
 public static void Save(string historyPath,string profilePath,ShowOutcome outcome,out LearningReport report){var history=File.Exists(historyPath)?JsonSerializer.Deserialize<List<ShowOutcome>>(File.ReadAllText(historyPath))??[]:[];history.RemoveAll(x=>x.Week==outcome.Week);history.Add(outcome);history=history.OrderBy(x=>x.Week).ToList();report=Learn(history);var options=new JsonSerializerOptions{WriteIndented=true};File.WriteAllText(historyPath,JsonSerializer.Serialize(history,options));File.WriteAllText(profilePath,JsonSerializer.Serialize(report.Profile,options));}
 public static LearningProfile LoadProfile(string path){try{return File.Exists(path)?JsonSerializer.Deserialize<LearningProfile>(File.ReadAllText(path))??LearningProfile.Empty():LearningProfile.Empty();}catch{return LearningProfile.Empty();}}
 static string[] Lines(string text)=>text.Replace("\r","").Split('\n',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries);
 static void Add(Dictionary<string,LearnedMetric> map,string key,double value)=>map[key]=map.TryGetValue(key,out var metric)?metric.Add(value):new(1,value);
}
