using System.IO;
using System.Windows;
using System.Windows.Input;
using System.Windows.Interop;
using System.Text.Json;
using System.Diagnostics;
using System.Reflection;
namespace MyGM.Companion;
public partial class MainWindow : Window {
 readonly WindowCaptureService capture=new(); readonly OcrProcessService ocr=new(); readonly OverlayWindow overlay=new(); CancellationTokenSource? operation; WindowInfo? current;
 readonly string root=AppContext.BaseDirectory, cacheDir, logDir, dataDir, diagnosticStatePath, planPath, rosterPath, objectivesPath;
 const int HotkeyId=106, WmHotkey=0x0312;
 public MainWindow(){InitializeComponent();cacheDir=Path.Combine(root,"cache");logDir=Path.Combine(root,"logs");dataDir=Path.Combine(root,"data");diagnosticStatePath=Path.Combine(dataDir,"diagnostic-state.json");planPath=Path.Combine(dataDir,"show-plan.json");rosterPath=Path.Combine(dataDir,"roster.json");objectivesPath=Path.Combine(dataDir,"objectives.json");Directory.CreateDirectory(cacheDir);Directory.CreateDirectory(logDir);Directory.CreateDirectory(dataDir);PreviewKeyDown+=OnKey;SourceInitialized+=RegisterInsertHotkey;LoadLocalState();Append("V10.9.0 gestartet. Overlay aus. Keine automatische Erkennung aktiv.");}
 void RegisterInsertHotkey(object? sender,EventArgs e){var h=new WindowInteropHelper(this).Handle;var source=HwndSource.FromHwnd(h);source.AddHook(WindowMessage);if(NativeMethods.RegisterHotKey(h,HotkeyId,0,0x2D))Append("INSERT registriert (Windows-Hotkey, kein Input-Hook).");else Append("INSERT konnte nicht global registriert werden; Umschalten bleibt in der App möglich.");}
 IntPtr WindowMessage(IntPtr hwnd,int msg,IntPtr wParam,IntPtr lParam,ref bool handled){if(msg==WmHotkey&&wParam.ToInt32()==HotkeyId){ToggleOverlay();handled=true;}return IntPtr.Zero;}
 void OnKey(object s,KeyEventArgs e){if(e.Key==Key.Insert){ToggleOverlay();e.Handled=true;}}
 void ToggleOverlay(){if(overlay.IsVisible){overlay.Hide();OverlayState.Text="Aus · INSERT";}else{overlay.Show();OverlayState.Text="An · INSERT";}}
 void Overlay_Click(object s,RoutedEventArgs e)=>ToggleOverlay();
 void Diagnostics_Click(object s,RoutedEventArgs e)=>ShowDiag();
 void Dashboard_Click(object s,RoutedEventArgs e){HidePanels();DashboardPanel.Visibility=Visibility.Visible;RefreshDashboard();}
 void Planning_Click(object s,RoutedEventArgs e){HidePanels();PlanningPanel.Visibility=Visibility.Visible;}
 void Roster_Click(object s,RoutedEventArgs e){HidePanels();RosterPanel.Visibility=Visibility.Visible;}
 void Objectives_Click(object s,RoutedEventArgs e){HidePanels();ObjectivesPanel.Visibility=Visibility.Visible;}
 void Updates_Click(object s,RoutedEventArgs e){try{var updater=Path.Combine(root,"Updater.exe");if(!File.Exists(updater))throw new FileNotFoundException("Updater.exe fehlt.");var temp=Path.Combine(Path.GetTempPath(),"MyGM-Updater-"+Guid.NewGuid().ToString("N")+".exe");File.Copy(updater,temp,true);var version=Assembly.GetExecutingAssembly().GetName().Version?.ToString(3)??"0.0.0";Process.Start(new ProcessStartInfo(temp,$"--install-dir \"{root.TrimEnd(Path.DirectorySeparatorChar)}\" --current-version {version} --app-pid {Environment.ProcessId}"){UseShellExecute=true});}catch(Exception ex){MessageBox.Show(ex.Message,"Updater",MessageBoxButton.OK,MessageBoxImage.Error);}}
 void ShowDiag(){HidePanels();DiagnosticsPanel.Visibility=Visibility.Visible;}
 void HidePanels(){DiagnosticsPanel.Visibility=Visibility.Collapsed;DashboardPanel.Visibility=Visibility.Collapsed;PlanningPanel.Visibility=Visibility.Collapsed;RosterPanel.Visibility=Visibility.Collapsed;ObjectivesPanel.Visibility=Visibility.Collapsed;}
 async void Find_Click(object s,RoutedEventArgs e){await Run(async token=>{StatusText.Text="Suche…";current=await capture.FindWweWindowAsync(token).WaitAsync(TimeSpan.FromSeconds(4),token);if(current is null){StatusText.Text="Nicht gefunden";DetailsText.Text="Das echte WWE-2K26-Spiel starten und bis zum Menü warten. Companion- und Setup-Fenster werden ignoriert.";Append("Kein echter WWE2K26-Spielprozess gefunden.");return;}StatusText.Text="Gefunden";DetailsText.Text=$"{current.Title}\nProzess: {current.ProcessName} (PID {current.ProcessId})\n{current.Width} × {current.Height} · {current.Mode}\nVordergrund: {(current.IsForeground?"Ja":"Nein")}";Append($"Spiel erkannt: {current.ProcessName}, {current.Title}, {current.Mode}, Vordergrund={current.IsForeground}");});}
 async void Capture_Click(object s,RoutedEventArgs e){await Run(async token=>{current??=await capture.FindWweWindowAsync(token).WaitAsync(TimeSpan.FromSeconds(4),token);if(current is null)throw new InvalidOperationException("Der echte WWE2K26-Spielprozess wurde nicht gefunden.");StatusText.Text="Capture läuft…";var result=await capture.CaptureAsync(current,cacheDir,token);PreviewImage.Source=result.Preview;StatusText.Text="Capture OK";DetailsText.Text=$"Hash: {result.Hash}\nDiagnose bestanden. Gezielter Spiel-Capture erfolgreich. Keine OCR ausgeführt.";SaveDiagnostic(result);RefreshDashboard();Append($"Screenshot gespeichert: {result.SavedPath}; Hash={result.Hash}");});}
 void SaveDiagnostic(CaptureResult result){var state=new DiagnosticState(true,DateTimeOffset.Now,result.Window.ProcessName,result.Window.Mode,result.Hash);File.WriteAllText(diagnosticStatePath,JsonSerializer.Serialize(state,new JsonSerializerOptions{WriteIndented=true}));}
 void SavePlan_Click(object s,RoutedEventArgs e){if(!decimal.TryParse(BudgetInput.Text,out var budget)){PlanSaveStatus.Text="Budget ist keine gültige Zahl.";return;}var plan=new ShowPlan(ShowNameInput.Text.Trim(),budget,GoalInput.Text.Trim(),RosterInput.Text,CardInput.Text,DateTimeOffset.Now);File.WriteAllText(planPath,JsonSerializer.Serialize(plan,new JsonSerializerOptions{WriteIndented=true}));PlanSaveStatus.Text="Lokal gespeichert · "+DateTime.Now.ToString("HH:mm:ss");RefreshDashboard();}
 async void RosterCapture_Click(object s,RoutedEventArgs e){await Run(async token=>{RosterStatus.Text="WWE-Fenster wird erfasst …";current=await capture.FindWweWindowAsync(token).WaitAsync(TimeSpan.FromSeconds(4),token);if(current is null)throw new InvalidOperationException("Der echte WWE2K26-Spielprozess wurde nicht gefunden.");var shot=await capture.CaptureAsync(current,cacheDir,token);RosterStatus.Text="OCR läuft im separaten Prozess …";var result=await ocr.RecognizeAsync(shot.SavedPath,token);if(!result.Ok)throw new InvalidOperationException(result.Error??"OCR fehlgeschlagen.");RosterEditor.Text=NormalizeOcr(result.Text);RosterStatus.Text=$"OCR-Vorschau ({result.Language}) – bitte prüfen und korrigieren.";Append($"On-Demand-OCR abgeschlossen: {result.Text.Length} Zeichen, Sprache={result.Language}");});}
 static string NormalizeOcr(string text)=>string.Join(Environment.NewLine,text.Replace("\r","").Split('\n',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).Where(x=>x.Length>1));
 void SaveRoster_Click(object s,RoutedEventArgs e){if(!int.TryParse(WeekInput.Text,out var week)||week<1){RosterStatus.Text="Woche ist ungültig.";return;}var rows=RosterEditor.Text.Replace("\r","").Split('\n',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries);var roster=new RosterSnapshot(BrandInput.Text.Trim(),week,rows,DateTimeOffset.Now);File.WriteAllText(rosterPath,JsonSerializer.Serialize(roster,new JsonSerializerOptions{WriteIndented=true}));RosterStatus.Text=$"{rows.Length} Zeilen lokal gespeichert.";}
 async void ObjectivesCapture_Click(object s,RoutedEventArgs e){await Run(async token=>{ObjectivesStatus.Text="Zielseite wird erfasst …";current=await capture.FindWweWindowAsync(token).WaitAsync(TimeSpan.FromSeconds(4),token);if(current is null)throw new InvalidOperationException("Der echte WWE2K26-Spielprozess wurde nicht gefunden.");var shot=await capture.CaptureAsync(current,cacheDir,token);ObjectivesStatus.Text="OCR läuft isoliert …";var result=await ocr.RecognizeAsync(shot.SavedPath,token);if(!result.Ok)throw new InvalidOperationException(result.Error??"OCR fehlgeschlagen.");ObjectivesRaw.Text=NormalizeOcr(result.Text);ParseObjectives();ObjectivesStatus.Text=$"Auswertung fertig ({result.Language}) – bitte bestätigen.";});}
 void ReparseObjectives_Click(object s,RoutedEventArgs e){ParseObjectives();ObjectivesStatus.Text="Originaltext neu ausgewertet.";}
 void ParseObjectives(){var week=int.TryParse(WeekInput.Text,out var w)&&w>0?w:1;var parsed=ObjectiveParser.Parse(ObjectivesRaw.Text,week);ObjectivesEditor.Text=string.Join(Environment.NewLine,parsed.Select(x=>x.ToEditorLine()));}
 void SaveObjectives_Click(object s,RoutedEventArgs e){var rows=ObjectivesEditor.Text.Replace("\r","").Split('\n',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries);var snapshot=new ObjectivesSnapshot(ObjectivesRaw.Text,rows,DateTimeOffset.Now);File.WriteAllText(objectivesPath,JsonSerializer.Serialize(snapshot,new JsonSerializerOptions{WriteIndented=true}));var urgent=rows.Where(r=>r.Contains("| Hoch |",StringComparison.OrdinalIgnoreCase)&&r.EndsWith("Offen",StringComparison.OrdinalIgnoreCase)).ToArray();if(urgent.Length>0)GoalInput.Text=string.Join("; ",urgent.Select(r=>r.Split('|')[2].Trim()));ObjectivesStatus.Text=$"{rows.Length} bestätigte Ziele gespeichert · {urgent.Length} hohe Priorität.";RefreshDashboard();}
 void LoadLocalState(){try{if(File.Exists(planPath)){var p=JsonSerializer.Deserialize<ShowPlan>(File.ReadAllText(planPath));if(p is not null){ShowNameInput.Text=p.ShowName;BudgetInput.Text=p.Budget.ToString();GoalInput.Text=p.CommissionerGoal;RosterInput.Text=p.RosterNotes;CardInput.Text=p.MatchCard;}}if(File.Exists(rosterPath)){var r=JsonSerializer.Deserialize<RosterSnapshot>(File.ReadAllText(rosterPath));if(r is not null){BrandInput.Text=r.Brand;WeekInput.Text=r.Week.ToString();RosterEditor.Text=string.Join(Environment.NewLine,r.Rows);}}if(File.Exists(objectivesPath)){var o=JsonSerializer.Deserialize<ObjectivesSnapshot>(File.ReadAllText(objectivesPath));if(o is not null){ObjectivesRaw.Text=o.RawText;ObjectivesEditor.Text=string.Join(Environment.NewLine,o.Rows);}}}catch(Exception ex){Append("Gespeicherte Daten konnten nicht geladen werden: "+ex.Message);}RefreshDashboard();}
 void RefreshDashboard(){DiagnosticState? d=null;ShowPlan? p=null;ObjectivesSnapshot? o=null;try{if(File.Exists(diagnosticStatePath))d=JsonSerializer.Deserialize<DiagnosticState>(File.ReadAllText(diagnosticStatePath));if(File.Exists(planPath))p=JsonSerializer.Deserialize<ShowPlan>(File.ReadAllText(planPath));if(File.Exists(objectivesPath))o=JsonSerializer.Deserialize<ObjectivesSnapshot>(File.ReadAllText(objectivesPath));}catch{}DashboardDiagnostic.Text=d?.Passed==true?$"Bestanden · {d.CompletedAt:dd.MM. HH:mm}":"Noch nicht bestanden";DashboardDiagnostic.Foreground=d?.Passed==true?System.Windows.Media.Brushes.LightGreen:System.Windows.Media.Brushes.Orange;var urgent=o?.Rows.Count(r=>r.Contains("| Hoch |",StringComparison.OrdinalIgnoreCase)&&r.EndsWith("Offen",StringComparison.OrdinalIgnoreCase))??0;DashboardObjectives.Text=o is null?"Keine bestätigten Ziele":$"{o.Rows.Length} Ziele · {urgent} mit hoher Priorität";DashboardShow.Text=p?.ShowName??"Noch keine Show gespeichert";DashboardBudget.Text=p is null?"Planung öffnen und ersten Plan anlegen.":$"Budget: {p.Budget:N0} $ · Ziel: {(string.IsNullOrWhiteSpace(p.CommissionerGoal)?"–":p.CommissionerGoal)}";}
 void Cancel_Click(object s,RoutedEventArgs e){operation?.Cancel();Append("Abbruch angefordert.");}
 async Task Run(Func<CancellationToken,Task> action){operation?.Cancel();operation=new();try{await action(operation.Token);}catch(OperationCanceledException){StatusText.Text="Abgebrochen";}catch(TimeoutException){StatusText.Text="Timeout";Append("Harter Timeout: Worker wurde abgebrochen.");}catch(Exception ex){StatusText.Text="Fehler";DetailsText.Text=ex.Message;Append("Fehler: "+ex.Message);}finally{operation.Dispose();operation=null;}}
 void Append(string message){var line=$"[{DateTime.Now:HH:mm:ss}] {message}";LogText.AppendText(line+Environment.NewLine);LogText.ScrollToEnd();try{Directory.CreateDirectory(logDir);File.AppendAllText(Path.Combine(logDir,$"diagnostic-{DateTime.Now:yyyyMMdd}.log"),line+Environment.NewLine);}catch{}}
 protected override void OnClosed(EventArgs e){operation?.Cancel();NativeMethods.UnregisterHotKey(new WindowInteropHelper(this).Handle,HotkeyId);overlay.Close();base.OnClosed(e);}
}
public sealed record DiagnosticState(bool Passed,DateTimeOffset CompletedAt,string ProcessName,string WindowMode,string CaptureHash);
public sealed record ShowPlan(string ShowName,decimal Budget,string CommissionerGoal,string RosterNotes,string MatchCard,DateTimeOffset SavedAt);
public sealed record RosterSnapshot(string Brand,int Week,string[] Rows,DateTimeOffset SavedAt);
public sealed record ObjectivesSnapshot(string RawText,string[] Rows,DateTimeOffset SavedAt);

