using System.IO;
using System.Windows;
using System.Windows.Input;
using System.Windows.Interop;
using System.Text.Json;
using System.Diagnostics;
using System.Reflection;
namespace MyGM.Companion;
public partial class MainWindow : Window {
 readonly WindowCaptureService capture=new(); readonly OcrProcessService ocr=new(); readonly OverlayWindow overlay=new(); readonly CancellationTokenSource updateCheckCts=new(); CancellationTokenSource? operation; WindowInfo? current;
 readonly string root=AppContext.BaseDirectory, cacheDir, logDir, dataDir, diagnosticStatePath, planPath, rosterPath, objectivesPath, historyPath, learningProfilePath;
 const int HotkeyId=106, WmHotkey=0x0312;
 public MainWindow(){InitializeComponent();cacheDir=Path.Combine(root,"cache");logDir=Path.Combine(root,"logs");dataDir=Path.Combine(root,"data");diagnosticStatePath=Path.Combine(dataDir,"diagnostic-state.json");planPath=Path.Combine(dataDir,"show-plan.json");rosterPath=Path.Combine(dataDir,"roster.json");objectivesPath=Path.Combine(dataDir,"objectives.json");historyPath=Path.Combine(dataDir,"show-history.json");learningProfilePath=Path.Combine(dataDir,"learning-profile.json");Directory.CreateDirectory(cacheDir);Directory.CreateDirectory(logDir);Directory.CreateDirectory(dataDir);PreviewKeyDown+=OnKey;SourceInitialized+=RegisterInsertHotkey;Loaded+=async(_,_)=>await RefreshUpdateBadgeAsync();LoadLocalState();LoadActiveCareerUi();Append("V11.4.1 gestartet. Overlay aus. Keine automatische Erkennung aktiv.");}
 void LoadActiveCareerUi(){var profile=CareerProfileService.LoadActive(dataDir);if(profile is null)return;if(profile.Id=="ecw-s1"&&(profile.RosterRows.Any(x=>x.StartsWith("Kevin Owens")&&!x.Contains("| 0 | Jimmy Uso"))||profile.RosterRows.Any(x=>x.StartsWith("Cody Rhodes")&&!x.Contains("| 0 | Kevin Owens")))){var corrected=CareerProfileService.CurrentEcwCalibration();profile=corrected with{Week=profile.Week,UpdatedAt=DateTimeOffset.Now};CareerProfileService.SaveActive(dataDir,profile);File.WriteAllText(rosterPath,JsonSerializer.Serialize(new RosterSnapshot(profile.Brand,profile.Week,profile.RosterRows,profile.UpdatedAt),new JsonSerializerOptions{WriteIndented=true}));}CareerNameInput.Text=profile.Name;BrandInput.Text=profile.Brand;WeekInput.Text=profile.Week.ToString();RosterEditor.Text=string.Join(Environment.NewLine,profile.RosterRows);RosterStatus.Text=$"Aktiver Spielstand: {profile.Name} · {profile.RosterRows.Length} Superstars · {profile.MatchSlots} Matches · {profile.PromoSlots} Promos";}
 async Task RefreshUpdateBadgeAsync(){var result=await UpdateCheckService.CheckAsync(updateCheckCts.Token);if(result.Available){UpdatesButton.Content=$"● UPDATE {result.Latest} VERFÜGBAR";UpdatesButton.Background=new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(211,43,43));UpdatesButton.BorderBrush=System.Windows.Media.Brushes.White;UpdatesButton.ToolTip="Neue Version auf GitHub gefunden – klicken zum Installieren";}else{UpdatesButton.Content="UPDATES · "+(result.Latest is null?"OFFLINE":"AKTUELL");UpdatesButton.ToolTip=result.Message;}}
 void RegisterInsertHotkey(object? sender,EventArgs e){var h=new WindowInteropHelper(this).Handle;var source=HwndSource.FromHwnd(h);source.AddHook(WindowMessage);if(NativeMethods.RegisterHotKey(h,HotkeyId,0,0x2D))Append("INSERT registriert (Windows-Hotkey, kein Input-Hook).");else Append("INSERT konnte nicht global registriert werden; Umschalten bleibt in der App möglich.");}
 IntPtr WindowMessage(IntPtr hwnd,int msg,IntPtr wParam,IntPtr lParam,ref bool handled){if(msg==WmHotkey&&wParam.ToInt32()==HotkeyId){ToggleOverlay();handled=true;}return IntPtr.Zero;}
 void OnKey(object s,KeyEventArgs e){if(e.Key==Key.Insert){ToggleOverlay();e.Handled=true;}}
 void ToggleOverlay(){if(overlay.IsVisible){overlay.Hide();OverlayState.Text="Aus · INSERT";}else{overlay.Show();OverlayState.Text="An · INSERT";}}
 void Overlay_Click(object s,RoutedEventArgs e)=>ToggleOverlay();
 void Diagnostics_Click(object s,RoutedEventArgs e)=>ShowDiag();
 void Dashboard_Click(object s,RoutedEventArgs e){HidePanels();DashboardPanel.Visibility=Visibility.Visible;RefreshDashboard();}
 void Planning_Click(object s,RoutedEventArgs e){HidePanels();PlanningPanel.Visibility=Visibility.Visible;}
 void Roster_Click(object s,RoutedEventArgs e){HidePanels();RosterPanel.Visibility=Visibility.Visible;}
 void Objectives_Click(object s,RoutedEventArgs e){HidePanels();ObjectivesPanel.Visibility=Visibility.Visible;RenderObjectiveCards(ObjectivesEditor.Text.Replace("\r","").Split('\n',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries));}
 void Analysis_Click(object s,RoutedEventArgs e){HidePanels();AnalysisPanel.Visibility=Visibility.Visible;}
 void Updates_Click(object s,RoutedEventArgs e){try{var updater=Path.Combine(root,"Updater.exe");if(!File.Exists(updater))throw new FileNotFoundException("Updater.exe fehlt.");var temp=Path.Combine(Path.GetTempPath(),"MyGM-Updater-"+Guid.NewGuid().ToString("N")+".exe");File.Copy(updater,temp,true);var version=Assembly.GetExecutingAssembly().GetName().Version?.ToString(3)??"0.0.0";Process.Start(new ProcessStartInfo(temp,$"--install-dir \"{root.TrimEnd(Path.DirectorySeparatorChar)}\" --current-version {version} --app-pid {Environment.ProcessId}"){UseShellExecute=true});}catch(Exception ex){MessageBox.Show(ex.Message,"Updater",MessageBoxButton.OK,MessageBoxImage.Error);}}
 void ShowDiag(){HidePanels();DiagnosticsPanel.Visibility=Visibility.Visible;}
 void HidePanels(){DiagnosticsPanel.Visibility=Visibility.Collapsed;DashboardPanel.Visibility=Visibility.Collapsed;PlanningPanel.Visibility=Visibility.Collapsed;RosterPanel.Visibility=Visibility.Collapsed;ObjectivesPanel.Visibility=Visibility.Collapsed;AnalysisPanel.Visibility=Visibility.Collapsed;}
 async void Find_Click(object s,RoutedEventArgs e){await Run(async token=>{StatusText.Text="Suche…";current=await capture.FindWweWindowAsync(token).WaitAsync(TimeSpan.FromSeconds(4),token);if(current is null){StatusText.Text="Nicht gefunden";DetailsText.Text="Das echte WWE-2K26-Spiel starten und bis zum Menü warten. Companion- und Setup-Fenster werden ignoriert.";Append("Kein echter WWE2K26-Spielprozess gefunden.");return;}StatusText.Text="Gefunden";DetailsText.Text=$"{current.Title}\nProzess: {current.ProcessName} (PID {current.ProcessId})\n{current.Width} × {current.Height} · {current.Mode}\nVordergrund: {(current.IsForeground?"Ja":"Nein")}";Append($"Spiel erkannt: {current.ProcessName}, {current.Title}, {current.Mode}, Vordergrund={current.IsForeground}");});}
 async void Capture_Click(object s,RoutedEventArgs e){await Run(async token=>{current??=await capture.FindWweWindowAsync(token).WaitAsync(TimeSpan.FromSeconds(4),token);if(current is null)throw new InvalidOperationException("Der echte WWE2K26-Spielprozess wurde nicht gefunden.");StatusText.Text="Capture läuft…";var result=await capture.CaptureAsync(current,cacheDir,token);PreviewImage.Source=result.Preview;StatusText.Text="Capture OK";DetailsText.Text=$"Hash: {result.Hash}\nDiagnose bestanden. Gezielter Spiel-Capture erfolgreich. Keine OCR ausgeführt.";SaveDiagnostic(result);RefreshDashboard();Append($"Screenshot gespeichert: {result.SavedPath}; Hash={result.Hash}");});}
 void SaveDiagnostic(CaptureResult result){var state=new DiagnosticState(true,DateTimeOffset.Now,result.Window.ProcessName,result.Window.Mode,result.Hash);File.WriteAllText(diagnosticStatePath,JsonSerializer.Serialize(state,new JsonSerializerOptions{WriteIndented=true}));}
 void SavePlan_Click(object s,RoutedEventArgs e){if(!decimal.TryParse(BudgetInput.Text,out var budget)){PlanSaveStatus.Text="Budget ist keine gültige Zahl.";return;}var plan=new ShowPlan(ShowNameInput.Text.Trim(),budget,GoalInput.Text.Trim(),RosterInput.Text,CardInput.Text,DateTimeOffset.Now);File.WriteAllText(planPath,JsonSerializer.Serialize(plan,new JsonSerializerOptions{WriteIndented=true}));PlanSaveStatus.Text="Lokal gespeichert · "+DateTime.Now.ToString("HH:mm:ss");RefreshDashboard();}
 void AutoPlan_Click(object s,RoutedEventArgs e){try{if(!decimal.TryParse(BudgetInput.Text,out var budget)||budget<0)throw new InvalidOperationException("Bitte das auf dem Showbild sichtbare Budget eintragen.");var profile=CareerProfileService.LoadActive(dataDir);if(profile is null&&!File.Exists(rosterPath))throw new InvalidOperationException("Zuerst den aktuellen Spielstand unter ROSTER & BRAND scannen oder übernehmen.");var roster=profile is null?JsonSerializer.Deserialize<RosterSnapshot>(File.ReadAllText(rosterPath))??throw new InvalidDataException("Rosterdatei ist ungültig."):new RosterSnapshot(profile.Brand,profile.Week,profile.RosterRows,profile.UpdatedAt);var objectives=File.Exists(objectivesPath)?JsonSerializer.Deserialize<ObjectivesSnapshot>(File.ReadAllText(objectivesPath)):null;var learning=LearningEngine.LoadProfile(learningProfilePath);var result=PlannerEngine.Generate(roster.Rows,objectives?.Rows??[],budget,learning,profile?.MatchSlots??4,profile?.PromoSlots??3);CardInput.Text=result.Render();RenderRecommendationCards(result);overlay.SetPlan(result,profile);RosterInput.Text=$"Spielstand: {profile?.Name??roster.Brand} · Woche: {roster.Week} · {roster.Rows.Length} Superstars · Show: {profile?.MatchSlots??4} Matches / {profile?.PromoSlots??3} Promos";PlanSaveStatus.Text=$"Empfehlung fertig · {result.Matches.Count} Matches · {result.Promos.Count} Promos · INSERT zeigt die vollständige Card";Append($"Auto-Plan: {result.Matches.Count} Matches, {result.Promos.Count} Promos, Kosten={result.EstimatedCost}, Lernshows={learning.Shows}");}catch(Exception ex){PlanSaveStatus.Text="Planung nicht möglich";MessageBox.Show(ex.Message,"Auto-Planer",MessageBoxButton.OK,MessageBoxImage.Warning);}}
 async void RosterCapture_Click(object s,RoutedEventArgs e){await Run(async token=>{RosterStatus.Text="Roster-Übersicht wird einmalig erfasst …";current=await capture.FindWweWindowAsync(token).WaitAsync(TimeSpan.FromSeconds(4),token);if(current is null)throw new InvalidOperationException("Der echte WWE2K26-Spielprozess wurde nicht gefunden.");var shot=await capture.CaptureAsync(current,cacheDir,token);var active=CareerProfileService.LoadActive(dataDir);var id=active?.Id??("career-"+DateTime.Now.ToString("yyyyMMdd-HHmmss"));var profileDir=Path.Combine(CareerProfileService.ProfilesDirectory(dataDir),id);RosterStatus.Text="15 Karten werden gezielt und getrennt gelesen …";var scan=await RosterCardScanner.ScanAsync(shot.SavedPath,profileDir,ocr,(done,total)=>Dispatcher.Invoke(()=>RosterStatus.Text=$"Roster-Scan: {done}/{total} Karten"),token);await File.WriteAllTextAsync(Path.Combine(profileDir,"last-roster-scan.json"),JsonSerializer.Serialize(scan,new JsonSerializerOptions{WriteIndented=true}),token);RosterEditor.Text=string.Join(Environment.NewLine,scan.Rows);CareerNameInput.Text=active?.Name??"Neuer Spielstand";var week=int.TryParse(WeekInput.Text,out var w)&&w>0?w:1;var updated=new CareerProfile(id,CareerNameInput.Text.Trim(),BrandInput.Text.Trim(),active?.Season??1,week,active?.MatchSlots??4,active?.PromoSlots??3,scan.Rows,scan.SourceHash,DateTimeOffset.Now);CareerProfileService.SaveActive(dataDir,updated);RosterStatus.Text=$"{scan.Rows.Length}/15 Karten erkannt · {scan.ReviewCount} Werte prüfen · Bilder lokal im Spielstand gespeichert";overlay.SetSummary($"{updated.Name}: {scan.Rows.Length} Superstars erkannt · Scan im Companion bestätigen");Append($"Gezielter Roster-Scan: {scan.Rows.Length}/15 erkannt, Prüffälle={scan.ReviewCount}, Hash={scan.SourceHash}");});}
 void UseCurrentEcw_Click(object s,RoutedEventArgs e){var profile=CareerProfileService.CurrentEcwCalibration();CareerProfileService.SaveActive(dataDir,profile);CareerNameInput.Text=profile.Name;BrandInput.Text=profile.Brand;WeekInput.Text=profile.Week.ToString();RosterEditor.Text=string.Join(Environment.NewLine,profile.RosterRows);var snapshot=new RosterSnapshot(profile.Brand,profile.Week,profile.RosterRows,DateTimeOffset.Now);File.WriteAllText(rosterPath,JsonSerializer.Serialize(snapshot,new JsonSerializerOptions{WriteIndented=true}));RosterStatus.Text=$"Aktiver Spielstand: {profile.Name} · {profile.RosterRows.Length} Superstars · {profile.MatchSlots} Matches · {profile.PromoSlots} Promos";overlay.SetSummary($"{profile.Name}: Roster bereit · jetzt Ziele scannen oder beste Card berechnen");RefreshDashboard();}
 static string NormalizeOcr(string text)=>string.Join(Environment.NewLine,text.Replace("\r","").Split('\n',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).Where(x=>x.Length>1));
 void RenderRecommendationCards(ShowRecommendation plan){RecommendationCards.Children.Clear();for(var i=0;i<plan.Matches.Count;i++){var match=plan.Matches[i];var title=i==0?"AUFTAKT":i==plan.Matches.Count-1?"HAUPTEVENT":$"MIDCARD {i}";RecommendationCards.Children.Add(UiCard(title,$"{match.A.Name}  VS.  {match.B.Name}",$"{match.MatchType} · {match.ExpectedMin:0.0}–{match.ExpectedMax:0.0} ★ · {match.Cost:N0} $",match.ExpectedMin>=4?"#173B2A":"#242838"));}for(var i=0;i<plan.Promos.Count;i++){var promo=plan.Promos[i];RecommendationCards.Children.Add(UiCard($"PROMO {i+1}",promo.Star.Name,promo.Type,"#251B36"));}foreach(var warning in plan.Warnings)RecommendationCards.Children.Add(UiCard("ACHTUNG",warning,"Vor dem Buchen prüfen","#482026"));}
 static System.Windows.Controls.Border UiCard(string eyebrow,string title,string detail,string color){var stack=new System.Windows.Controls.StackPanel();stack.Children.Add(new System.Windows.Controls.TextBlock{Text=eyebrow,Foreground=new System.Windows.Media.SolidColorBrush((System.Windows.Media.Color)System.Windows.Media.ColorConverter.ConvertFromString("#EF4348")),FontSize=11,FontWeight=FontWeights.Bold});stack.Children.Add(new System.Windows.Controls.TextBlock{Text=title,Foreground=System.Windows.Media.Brushes.White,FontSize=17,FontWeight=FontWeights.SemiBold,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,3,0,0)});stack.Children.Add(new System.Windows.Controls.TextBlock{Text=detail,Foreground=new System.Windows.Media.SolidColorBrush((System.Windows.Media.Color)System.Windows.Media.ColorConverter.ConvertFromString("#B7BECC")),FontSize=12,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,3,0,0)});return new System.Windows.Controls.Border{Background=new System.Windows.Media.SolidColorBrush((System.Windows.Media.Color)System.Windows.Media.ColorConverter.ConvertFromString(color)),BorderBrush=new System.Windows.Media.SolidColorBrush((System.Windows.Media.Color)System.Windows.Media.ColorConverter.ConvertFromString("#343A48")),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(8),Padding=new Thickness(12),Margin=new Thickness(0,0,0,8),Child=stack};}
 void RenderObjectiveCards(IEnumerable<string> rows){ObjectiveCards.Children.Clear();var parsed=rows.Select(row=>row.Split('|',StringSplitOptions.TrimEntries)).Where(p=>p.Length>=3).OrderBy(p=>p.Length>4&&p[4].Equals("Hoch",StringComparison.OrdinalIgnoreCase)?0:1).ThenBy(p=>p.Length>3&&int.TryParse(p[3],out var deadline)?deadline:int.MaxValue).ToArray();if(parsed.Length==0){ObjectiveCards.Children.Add(UiCard("NOCH NICHT ERKANNT","Keine sicheren Ziele vorhanden","Öffne im Spiel die Zielseite und klicke ZIELSEITE ERFASSEN.","#242838"));return;}foreach(var p in parsed){var type=p[0];var person=p.Length>1?p[1]:"Allgemein";var requirement=p[2];var deadline=p.Length>3?p[3]:"–";var priority=p.Length>4?p[4]:"Mittel";var status=p.Length>5?p[5]:"Offen";ObjectiveCards.Children.Add(UiCard($"{priority.ToUpperInvariant()} · {type.ToUpperInvariant()}",requirement,$"{person} · Deadline Woche {deadline} · {status}",priority.Equals("Hoch",StringComparison.OrdinalIgnoreCase)?"#482026":"#242838"));}}
 void SaveRoster_Click(object s,RoutedEventArgs e){if(!int.TryParse(WeekInput.Text,out var week)||week<1){RosterStatus.Text="Woche ist ungültig.";return;}var rows=RosterEditor.Text.Replace("\r","").Split('\n',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries);var roster=new RosterSnapshot(BrandInput.Text.Trim(),week,rows,DateTimeOffset.Now);File.WriteAllText(rosterPath,JsonSerializer.Serialize(roster,new JsonSerializerOptions{WriteIndented=true}));var id=string.Join("-",(CareerNameInput.Text+"-"+BrandInput.Text).ToLowerInvariant().Select(c=>char.IsLetterOrDigit(c)?c:'-')).Trim('-');var previous=CareerProfileService.LoadActive(dataDir);var profile=new CareerProfile(string.IsNullOrWhiteSpace(id)?Guid.NewGuid().ToString("N"):id,CareerNameInput.Text.Trim(),BrandInput.Text.Trim(),previous?.Season??1,week,previous?.MatchSlots??4,previous?.PromoSlots??3,rows,previous?.RosterCaptureHash,DateTimeOffset.Now);CareerProfileService.SaveActive(dataDir,profile);RosterStatus.Text=$"Spielstand gespeichert · {rows.Length} Superstars · gilt nur für {profile.Name}.";overlay.SetSummary($"{profile.Name}: Roster bereit · beste Card berechnen");}
 async void ObjectivesCapture_Click(object s,RoutedEventArgs e){await Run(async token=>{ObjectivesStatus.Text="Zielseite wird erfasst …";current=await capture.FindWweWindowAsync(token).WaitAsync(TimeSpan.FromSeconds(4),token);if(current is null)throw new InvalidOperationException("Der echte WWE2K26-Spielprozess wurde nicht gefunden.");var shot=await capture.CaptureAsync(current,cacheDir,token);ObjectivesStatus.Text="OCR läuft isoliert …";var result=await ocr.RecognizeAsync(shot.SavedPath,token);if(!result.Ok)throw new InvalidOperationException(result.Error??"OCR fehlgeschlagen.");ObjectivesRaw.Text=NormalizeOcr(result.Text);ParseObjectives();ObjectivesStatus.Text=$"Auswertung fertig ({result.Language}) – bitte bestätigen.";});}
 void ReparseObjectives_Click(object s,RoutedEventArgs e){ParseObjectives();ObjectivesStatus.Text="Originaltext neu ausgewertet.";}
 void ParseObjectives(){var week=int.TryParse(WeekInput.Text,out var w)&&w>0?w:1;var parsed=ObjectiveParser.Parse(ObjectivesRaw.Text,week);var rows=parsed.Select(x=>x.ToEditorLine()).ToArray();ObjectivesEditor.Text=string.Join(Environment.NewLine,rows);RenderObjectiveCards(rows);}
 void SaveObjectives_Click(object s,RoutedEventArgs e){var rows=ObjectivesEditor.Text.Replace("\r","").Split('\n',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries);var snapshot=new ObjectivesSnapshot(ObjectivesRaw.Text,rows,DateTimeOffset.Now);File.WriteAllText(objectivesPath,JsonSerializer.Serialize(snapshot,new JsonSerializerOptions{WriteIndented=true}));var urgent=rows.Where(r=>r.Contains("| Hoch |",StringComparison.OrdinalIgnoreCase)&&r.EndsWith("Offen",StringComparison.OrdinalIgnoreCase)).ToArray();if(urgent.Length>0)GoalInput.Text=string.Join("; ",urgent.Select(r=>r.Split('|')[2].Trim()));ObjectivesStatus.Text=$"{rows.Length} bestätigte Ziele gespeichert · {urgent.Length} hohe Priorität.";RefreshDashboard();}
 async void ResultsCapture_Click(object s,RoutedEventArgs e){await Run(async token=>{AnalysisStatus.Text="Ergebnisbildschirm wird erfasst …";current=await capture.FindWweWindowAsync(token).WaitAsync(TimeSpan.FromSeconds(4),token);if(current is null)throw new InvalidOperationException("Der echte WWE2K26-Spielprozess wurde nicht gefunden.");var shot=await capture.CaptureAsync(current,cacheDir,token);AnalysisStatus.Text="OCR läuft isoliert …";var result=await ocr.RecognizeAsync(shot.SavedPath,token);if(!result.Ok)throw new InvalidOperationException(result.Error??"OCR fehlgeschlagen.");ResultsRaw.Text=NormalizeOcr(result.Text);AnalysisStatus.Text="OCR-Text erfasst – Match- und Promozeilen bitte bestätigen.";});}
 void AnalyzeResults_Click(object s,RoutedEventArgs e){try{var week=int.TryParse(WeekInput.Text,out var w)&&w>0?w:1;if(!double.TryParse(EndRatingInput.Text.Replace(',','.'),System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out var rating))throw new FormatException("Endwertung muss eine Zahl zwischen 0 und 5 sein.");var outcome=LearningEngine.Parse(week,MatchResultsEditor.Text,PromoResultsEditor.Text,rating,ResultsNotes.Text);LearningEngine.Save(historyPath,learningProfilePath,outcome,out var report);LearningReportText.Text=report.Summary+Environment.NewLine+Environment.NewLine+"STÄRKEN:"+Environment.NewLine+string.Join(Environment.NewLine,report.Strengths.Select(x=>"+ "+x))+Environment.NewLine+Environment.NewLine+"VERBESSERN:"+Environment.NewLine+string.Join(Environment.NewLine,report.Improvements.Select(x=>"- "+x));AnalysisStatus.Text=$"Woche {week} gespeichert · Lernprofil aktualisiert.";RefreshDashboard();}catch(Exception ex){MessageBox.Show(ex.Message,"Showanalyse",MessageBoxButton.OK,MessageBoxImage.Warning);AnalysisStatus.Text="Bitte Ergebnisdaten korrigieren.";}}
 void LoadLocalState(){try{if(File.Exists(planPath)){var p=JsonSerializer.Deserialize<ShowPlan>(File.ReadAllText(planPath));if(p is not null){ShowNameInput.Text=p.ShowName;BudgetInput.Text=p.Budget.ToString();GoalInput.Text=p.CommissionerGoal;RosterInput.Text=p.RosterNotes;CardInput.Text=p.MatchCard;}}if(File.Exists(rosterPath)){var r=JsonSerializer.Deserialize<RosterSnapshot>(File.ReadAllText(rosterPath));if(r is not null){BrandInput.Text=r.Brand;WeekInput.Text=r.Week.ToString();RosterEditor.Text=string.Join(Environment.NewLine,r.Rows);}}if(File.Exists(objectivesPath)){var o=JsonSerializer.Deserialize<ObjectivesSnapshot>(File.ReadAllText(objectivesPath));if(o is not null){ObjectivesRaw.Text=o.RawText;ObjectivesEditor.Text=string.Join(Environment.NewLine,o.Rows);}}}catch(Exception ex){Append("Gespeicherte Daten konnten nicht geladen werden: "+ex.Message);}RefreshDashboard();}
 void RefreshDashboard(){DiagnosticState? d=null;ShowPlan? p=null;ObjectivesSnapshot? o=null;try{if(File.Exists(diagnosticStatePath))d=JsonSerializer.Deserialize<DiagnosticState>(File.ReadAllText(diagnosticStatePath));if(File.Exists(planPath))p=JsonSerializer.Deserialize<ShowPlan>(File.ReadAllText(planPath));if(File.Exists(objectivesPath))o=JsonSerializer.Deserialize<ObjectivesSnapshot>(File.ReadAllText(objectivesPath));}catch{}DashboardDiagnostic.Text=d?.Passed==true?$"Bestanden · {d.CompletedAt:dd.MM. HH:mm}":"Noch nicht bestanden";DashboardDiagnostic.Foreground=d?.Passed==true?System.Windows.Media.Brushes.LightGreen:System.Windows.Media.Brushes.Orange;var urgent=o?.Rows.Count(r=>r.Contains("| Hoch |",StringComparison.OrdinalIgnoreCase)&&r.EndsWith("Offen",StringComparison.OrdinalIgnoreCase))??0;DashboardObjectives.Text=o is null?"Keine bestätigten Ziele":$"{o.Rows.Length} Ziele · {urgent} mit hoher Priorität";DashboardShow.Text=p?.ShowName??"Noch keine Show gespeichert";DashboardBudget.Text=p is null?"Planung öffnen und ersten Plan anlegen.":$"Budget: {p.Budget:N0} $ · Ziel: {(string.IsNullOrWhiteSpace(p.CommissionerGoal)?"–":p.CommissionerGoal)}";var learning=LearningEngine.LoadProfile(learningProfilePath);DashboardLearning.Text=learning.Shows==0?"Noch keine Lerndaten":$"Lernprofil: {learning.Shows} Shows · Endwertung Ø {learning.AverageEndRating:0.0}/5";}
 void Cancel_Click(object s,RoutedEventArgs e){operation?.Cancel();Append("Abbruch angefordert.");}
 async Task Run(Func<CancellationToken,Task> action){operation?.Cancel();operation=new();try{await action(operation.Token);}catch(OperationCanceledException){StatusText.Text="Abgebrochen";}catch(TimeoutException){StatusText.Text="Timeout";Append("Harter Timeout: Worker wurde abgebrochen.");}catch(Exception ex){StatusText.Text="Fehler";DetailsText.Text=ex.Message;Append("Fehler: "+ex.Message);}finally{operation.Dispose();operation=null;}}
 void Append(string message){var line=$"[{DateTime.Now:HH:mm:ss}] {message}";LogText.AppendText(line+Environment.NewLine);LogText.ScrollToEnd();try{Directory.CreateDirectory(logDir);File.AppendAllText(Path.Combine(logDir,$"diagnostic-{DateTime.Now:yyyyMMdd}.log"),line+Environment.NewLine);}catch{}}
 protected override void OnClosed(EventArgs e){operation?.Cancel();updateCheckCts.Cancel();updateCheckCts.Dispose();NativeMethods.UnregisterHotKey(new WindowInteropHelper(this).Handle,HotkeyId);overlay.Shutdown();base.OnClosed(e);}
}
public sealed record DiagnosticState(bool Passed,DateTimeOffset CompletedAt,string ProcessName,string WindowMode,string CaptureHash);
public sealed record ShowPlan(string ShowName,decimal Budget,string CommissionerGoal,string RosterNotes,string MatchCard,DateTimeOffset SavedAt);
public sealed record RosterSnapshot(string Brand,int Week,string[] Rows,DateTimeOffset SavedAt);
public sealed record ObjectivesSnapshot(string RawText,string[] Rows,DateTimeOffset SavedAt);
