using System.Globalization;
namespace MyGM.Companion;

public sealed record Superstar(string Name,string Gender,string Role,string Style,int Popularity,int Stamina,string Manager,int Rivalry);
public sealed record PlannedMatch(Superstar A,Superstar B,string MatchType,int Cost,double Score,double ExpectedMin,double ExpectedMax,string Reason);
public sealed record PlannedPromo(Superstar Star,string Type,double Score,string Reason);
public sealed record ShowRecommendation(IReadOnlyList<PlannedMatch> Matches,IReadOnlyList<PlannedPromo> Promos,int EstimatedCost,IReadOnlyList<string> Warnings,string Summary){
 public string Render(){var lines=new List<string>{Summary,""};var slots=new[]{"OPENER","MIDCARD 1","MIDCARD 2","MAIN EVENT"};for(var i=0;i<Matches.Count;i++){var m=Matches[i];lines.Add($"{slots[Math.Min(i,slots.Length-1)]}: {m.A.Name} vs. {m.B.Name} – {m.MatchType}");lines.Add($"  Erwartung: {m.ExpectedMin:0.0}–{m.ExpectedMax:0.0} ★ · Kosten: {m.Cost:N0} $");if(!string.IsNullOrWhiteSpace(m.A.Manager)||!string.IsNullOrWhiteSpace(m.B.Manager))lines.Add($"  Manager: {ManagerText(m.A)} | {ManagerText(m.B)}");lines.Add($"  Warum: {m.Reason}");lines.Add("");}for(var i=0;i<Promos.Count;i++){var p=Promos[i];lines.Add($"PROMO {i+1}: {p.Star.Name} – {p.Type}");lines.Add($"  Warum: {p.Reason}");}lines.Add("");lines.Add($"GESCHÄTZTE MATCHKOSTEN: {EstimatedCost:N0} $");if(Warnings.Count>0){lines.Add("");lines.Add("WICHTIGE HINWEISE:");lines.AddRange(Warnings.Select(x=>"- "+x));}return string.Join(Environment.NewLine,lines);}
 static string ManagerText(Superstar s)=>string.IsNullOrWhiteSpace(s.Manager)?$"{s.Name}: keiner":$"{s.Name}: {s.Manager}";
}

public static class PlannerEngine {
 static readonly Dictionary<string,int> MatchCosts=new(StringComparer.OrdinalIgnoreCase){{"Normal",0},{"Tables",5_000},{"Extreme Rules",7_500},{"TLC",10_000},{"Steel Cage",12_500},{"Hell in a Cell",20_000}};
 public static bool TryParseRoster(IEnumerable<string> rows,out List<Superstar> stars,out List<string> errors){stars=[];errors=[];var lineNo=0;foreach(var row in rows){lineNo++;var p=row.Split('|',StringSplitOptions.TrimEntries);try{string name,gender,role,style,manager;int pop,stamina,rivalry;if(p.Length>=8){name=p[0];gender=NormalizeGender(p[1]);role=NormalizeRole(p[2]);style=NormalizeStyle(p[3]);pop=ParseNumber(p[4]);stamina=ParseNumber(p[5]);manager=DashToEmpty(p[6]);rivalry=ParseOptional(p[7]);}else if(p.Length>=6){name=p[0];gender="Unbekannt";role=NormalizeRole(p[1]);style=NormalizeStyle(p[2]);pop=ParseNumber(p[3]);stamina=ParseNumber(p[4]);manager=DashToEmpty(p[5]);rivalry=0;}else{errors.Add($"Rosterzeile {lineNo}: Zu wenige Felder.");continue;}if(string.IsNullOrWhiteSpace(name))throw new FormatException("Name fehlt");if(role=="Unbekannt")errors.Add($"{name}: Rolle sollte Face oder Heel sein.");if(style=="Unbekannt")errors.Add($"{name}: Klasse wurde nicht erkannt.");if(gender=="Unbekannt")errors.Add($"{name}: Geschlecht fehlt; bitte das neue 8-Spalten-Format verwenden.");stars.Add(new(name,gender,role,style,Math.Clamp(pop,0,100),Math.Clamp(stamina,0,100),manager,Math.Clamp(rivalry,0,4)));}catch(Exception ex){errors.Add($"Rosterzeile {lineNo}: {ex.Message}");}}return stars.Count>=4;}
 public static ShowRecommendation Generate(IEnumerable<string> rosterRows,IEnumerable<string> objectiveRows,decimal budget){if(!TryParseRoster(rosterRows,out var stars,out var warnings))throw new InvalidOperationException("Mindestens vier gültige Superstar-Zeilen werden benötigt.\n"+string.Join("\n",warnings));var objectives=objectiveRows.ToArray();var forcedType=FindForcedMatchType(objectives);var candidates=new List<PlannedMatch>();for(var i=0;i<stars.Count;i++)for(var j=i+1;j<stars.Count;j++){var a=stars[i];var b=stars[j];if(!CanFight(a,b))continue;var matchType=SelectMatchType(a,b,null,budget);var cost=MatchCosts[matchType];var score=ScorePair(a,b,matchType,out var reason);var expected=Math.Clamp(1.4+score/32d,1.5,5);candidates.Add(new(a,b,matchType,cost,score,Math.Max(1.5,expected-.35),Math.Min(5,expected+.35),reason));}if(candidates.Count<2)throw new InvalidOperationException("Es gibt zu wenige gültige Paarungen. Geschlecht, Rolle und Klasse im Roster prüfen.");
  var selected=new List<PlannedMatch>();var used=new HashSet<string>(StringComparer.OrdinalIgnoreCase);var remaining=(int)Math.Max(0,budget);foreach(var c in candidates.OrderByDescending(x=>x.Score)){if(used.Contains(c.A.Name)||used.Contains(c.B.Name)||c.Cost>remaining)continue;selected.Add(c);used.Add(c.A.Name);used.Add(c.B.Name);remaining-=c.Cost;if(selected.Count==4)break;}if(forcedType is not null&&!selected.Any(x=>x.MatchType.Equals(forcedType,StringComparison.OrdinalIgnoreCase))&&MatchCosts.TryGetValue(forcedType,out var forcedCost)){var target=selected.Where(x=>Math.Min(x.A.Stamina,x.B.Stamina)>=45).OrderByDescending(x=>x.Score).FirstOrDefault();if(target is not null&&remaining+target.Cost>=forcedCost){var index=selected.IndexOf(target);selected[index]=target with{MatchType=forcedType,Cost=forcedCost,Score=target.Score+4,ExpectedMin=Math.Min(5,target.ExpectedMin+.1),ExpectedMax=Math.Min(5,target.ExpectedMax+.15),Reason=target.Reason+"; Matchtyp wegen offenem Ziel"};remaining+=target.Cost-forcedCost;}else warnings.Add($"Matchtyp-Ziel '{forcedType}' konnte wegen Budget oder Ausdauer nicht sicher eingeplant werden.");}if(selected.Count<4)warnings.Add($"Nur {selected.Count} konfliktfreie Matches möglich; für vier Matches werden mindestens acht passende, einsatzfähige Superstars benötigt.");
  selected=ArrangeCard(selected);var promos=stars.Where(s=>!used.Contains(s.Name)&&s.Stamina>=20).OrderByDescending(s=>PromoScore(s,objectives)).Take(3).Select(s=>BuildPromo(s,objectives)).ToList();ApplyObjectiveWarnings(objectives,selected,promos,warnings);var avg=selected.Count==0?0:selected.Average(x=>(x.ExpectedMin+x.ExpectedMax)/2);var summary=$"AUTO-PLAN · {selected.Count} Matches · {promos.Count} Promos · erwarteter Matchschnitt {avg:0.0} ★";return new(selected,promos,selected.Sum(x=>x.Cost),warnings.Distinct().ToList(),summary);}
 static bool CanFight(Superstar a,Superstar b){if(a.Stamina<20||b.Stamina<20)return false;if(a.Gender!="Unbekannt"&&b.Gender!="Unbekannt"&&!a.Gender.Equals(b.Gender,StringComparison.OrdinalIgnoreCase))return false;return true;}
 static double ScorePair(Superstar a,Superstar b,string type,out string reason){var compatibility=Compatibility(a.Style,b.Style);var role=a.Role!=b.Role&&a.Role!="Unbekannt"&&b.Role!="Unbekannt"?14:2;var pop=(a.Popularity+b.Popularity)/4d;var stamina=Math.Min(a.Stamina,b.Stamina)/8d;var rivalry=Math.Max(a.Rivalry,b.Rivalry)*5;var typeFit=type=="Normal"?3:Math.Min(a.Stamina,b.Stamina)>=55?8:-8;var manager=(!string.IsNullOrWhiteSpace(a.Manager)||!string.IsNullOrWhiteSpace(b.Manager))?2:0;var score=compatibility+role+pop+stamina+rivalry+typeFit+manager;reason=$"Klassen {a.Style}/{b.Style}, {(role>=14?"Face/Heel passt":"gleiche/unklare Rolle")}, POP Ø {(a.Popularity+b.Popularity)/2}, Ausdauer min. {Math.Min(a.Stamina,b.Stamina)}, Rivalität {Math.Max(a.Rivalry,b.Rivalry)}";return score;}
 static int Compatibility(string a,string b){if(a=="Specialist"||b=="Specialist")return 16;if((a=="Fighter"&&b=="Bruiser")||(a=="Bruiser"&&b=="Fighter"))return 22;if((a=="Cruiser"&&b=="Giant")||(a=="Giant"&&b=="Cruiser"))return 22;return a==b?2:8;}
 static string SelectMatchType(Superstar a,Superstar b,string? forced,decimal budget){var min=Math.Min(a.Stamina,b.Stamina);if(forced is not null&&MatchCosts.TryGetValue(forced,out var forcedCost)&&min>=45&&budget>=forcedCost)return forced;if(min>=75&&Math.Max(a.Rivalry,b.Rivalry)>=3&&budget>=20_000)return "Hell in a Cell";if(min>=68&&Math.Max(a.Rivalry,b.Rivalry)>=2&&budget>=10_000)return "TLC";if(min>=58&&budget>=7_500)return "Extreme Rules";if(min>=48&&budget>=5_000)return "Tables";return "Normal";}
 static List<PlannedMatch> ArrangeCard(List<PlannedMatch> chosen){var sorted=chosen.OrderByDescending(x=>x.Score).ToList();if(sorted.Count<=1)return sorted;var main=sorted[0];var opener=sorted[1];var middle=sorted.Skip(2).OrderBy(x=>x.Score).ToList();var result=new List<PlannedMatch>{opener};result.AddRange(middle);result.Add(main);return result;}
 static double PromoScore(Superstar s,string[] objectives)=>s.Popularity+(s.Stamina<45?15:0)+(objectives.Any(o=>o.Contains(s.Name,StringComparison.OrdinalIgnoreCase))?20:0);
 static PlannedPromo BuildPromo(Superstar s,string[] objectives){var own=objectives.FirstOrDefault(o=>o.Contains(s.Name,StringComparison.OrdinalIgnoreCase));var type=own?.Contains("Rollenwechsel",StringComparison.OrdinalIgnoreCase)==true?"Rollenwechsel":s.Stamina<45?"Eigenwerbung":"Call-Out";return new(s,type,PromoScore(s,objectives),own is null?"Nicht im Match; Popularität aufbauen und Match-Ausdauer sparen.":"Offenes Ziel oder Versprechen dieses Superstars berücksichtigen.");}
 static string? FindForcedMatchType(string[] rows){foreach(var name in MatchCosts.Keys.Where(x=>x!="Normal"))if(rows.Any(r=>r.Contains(name,StringComparison.OrdinalIgnoreCase)))return name;return null;}
 static void ApplyObjectiveWarnings(string[] objectives,List<PlannedMatch> matches,List<PlannedPromo> promos,List<string> warnings){foreach(var row in objectives.Where(x=>x.EndsWith("Offen",StringComparison.OrdinalIgnoreCase))){var parts=row.Split('|',StringSplitOptions.TrimEntries);var requirement=parts.Length>2?parts[2]:row;if(row.Contains("Eingriff",StringComparison.OrdinalIgnoreCase))warnings.Add("Eingriffsziel erkannt: Eingriff im Spiel manuell auf einen passenden Gegner setzen; Gewinner-Versprechen dabei nicht gefährden.");else if(row.Contains("Sieg",StringComparison.OrdinalIgnoreCase)&&!matches.Any(m=>requirement.Contains(m.A.Name,StringComparison.OrdinalIgnoreCase)||requirement.Contains(m.B.Name,StringComparison.OrdinalIgnoreCase)))warnings.Add("Siegversprechen möglicherweise nicht eingeplant: "+requirement);else if(row.Contains("Ruhe",StringComparison.OrdinalIgnoreCase)&&matches.Any(m=>requirement.Contains(m.A.Name,StringComparison.OrdinalIgnoreCase)||requirement.Contains(m.B.Name,StringComparison.OrdinalIgnoreCase)))warnings.Add("Konflikt: Ruheforderung kollidiert mit einem geplanten Match – Card vor dem Buchen prüfen.");else if(row.Contains("Rollenwechsel",StringComparison.OrdinalIgnoreCase)&&!promos.Any(p=>requirement.Contains(p.Star.Name,StringComparison.OrdinalIgnoreCase)))warnings.Add("Rollenwechselziel benötigt möglicherweise eine manuelle Promo-Zuweisung: "+requirement);}}
 static int ParseNumber(string value){var digits=new string(value.Where(char.IsDigit).ToArray());return int.TryParse(digits,NumberStyles.Integer,CultureInfo.InvariantCulture,out var n)?n:throw new FormatException($"Zahl ungültig: {value}");}
 static int ParseOptional(string value)=>value is "" or "–" or "-"?0:ParseNumber(value);
 static string DashToEmpty(string value)=>value is "–" or "-"?"":value.Trim();
 static string NormalizeGender(string value)=>value.Trim().ToLowerInvariant() switch{"m" or "mann" or "male" or "men"=>"Männlich","w" or "frau" or "female" or "women"=>"Weiblich",_=>"Unbekannt"};
 static string NormalizeRole(string value)=>value.Trim().ToLowerInvariant() switch{"face" or "good" or "gut"=>"Face","heel" or "bad" or "böse" or "boese"=>"Heel",_=>"Unbekannt"};
 static string NormalizeStyle(string value)=>value.Trim().ToLowerInvariant() switch{"fighter" or "kämpfer" or "kaempfer"=>"Fighter","bruiser" or "schläger" or "schlaeger"=>"Bruiser","cruiser" or "cruiserweight"=>"Cruiser","giant" or "riese"=>"Giant","specialist" or "spezialist"=>"Specialist",_=>"Unbekannt"};
}

