using Microsoft.Win32;
using System.IO.Compression;
using System.Reflection;
using System.Windows.Forms;

internal static class Program {
 [STAThread]
 public static void Main(){ApplicationConfiguration.Initialize();Application.Run(new SetupForm());}
}
sealed class SetupForm:Form {
 readonly TextBox path=new(){Dock=DockStyle.Top,Text=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"MyGM Companion")}; readonly CheckBox shortcut=new(){Text="Desktop-Verknüpfung erstellen",Checked=true,AutoSize=true}; readonly ProgressBar progress=new(){Dock=DockStyle.Bottom,Style=ProgressBarStyle.Marquee,Visible=false}; readonly Button install=new(){Text="Installieren",Width=130,Height=36};
 public SetupForm(){Text="WWE 2K26 MyGM Companion V11.4.1 Setup";Width=620;Height=300;StartPosition=FormStartPosition.CenterScreen;FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;Icon=System.Drawing.Icon.ExtractAssociatedIcon(Application.ExecutablePath);BackColor=System.Drawing.Color.FromArgb(8,10,15);ForeColor=System.Drawing.Color.White;
  var title=new Label(){Text="MYGM COMPANION 11.4.1",Font=new System.Drawing.Font("Segoe UI",20,System.Drawing.FontStyle.Bold),ForeColor=System.Drawing.Color.FromArgb(239,45,52),AutoSize=true,Top=22,Left=24};var label=new Label(){Text="Installationspfad",AutoSize=true,Top=86,Left=24};path.SetBounds(24,108,470,30);var browse=new Button(){Text="…",Left=505,Top=106,Width=55,Height=30};shortcut.SetBounds(24,155,300,25);install.SetBounds(430,190,130,36);install.BackColor=System.Drawing.Color.FromArgb(227,27,35);install.ForeColor=System.Drawing.Color.White;Controls.AddRange([title,label,path,browse,shortcut,install,progress]);browse.Click+=Browse;install.Click+=Install;}
 void Browse(object? s,EventArgs e){using var f=new FolderBrowserDialog(){SelectedPath=Directory.Exists(path.Text)?path.Text:Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),Description="Installationsordner wählen",ShowNewFolderButton=true,UseDescriptionForTitle=true};if(f.ShowDialog(this)==DialogResult.OK)path.Text=Path.Combine(f.SelectedPath,"MyGM Companion");}
 async void Install(object? s,EventArgs e){string target;try{target=Path.GetFullPath(path.Text);}catch{MessageBox.Show("Bitte einen gültigen Installationspfad wählen.");return;}if(target.Length<4){MessageBox.Show("Bitte einen gültigen Installationspfad wählen.");return;}var createShortcut=shortcut.Checked;install.Enabled=false;progress.Visible=true;try{await Task.Run(()=>DoInstall(target,createShortcut));MessageBox.Show("Installation abgeschlossen.","MyGM Companion",MessageBoxButtons.OK,MessageBoxIcon.Information);System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(Path.Combine(target,"MyGMCompanion.exe")){UseShellExecute=true});Close();}catch(Exception ex){MessageBox.Show("Installation fehlgeschlagen: "+ex.Message,"Setup",MessageBoxButtons.OK,MessageBoxIcon.Error);install.Enabled=true;progress.Visible=false;}}
 void DoInstall(string target,bool createDesktopShortcut){Directory.CreateDirectory(target);using var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream("payload.zip")??throw new InvalidOperationException("Installationsdaten fehlen.");using var zip=new ZipArchive(stream);foreach(var entry in zip.Entries){var dest=Path.GetFullPath(Path.Combine(target,entry.FullName));if(!dest.StartsWith(target,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("Ungültiger Paketpfad.");if(string.IsNullOrEmpty(entry.Name)){Directory.CreateDirectory(dest);continue;}Directory.CreateDirectory(Path.GetDirectoryName(dest)!);entry.ExtractToFile(dest,true);}foreach(var dir in new[]{"assets","config","data","cache","logs"})Directory.CreateDirectory(Path.Combine(target,dir));
  if(createDesktopShortcut)CreateShortcut(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),"WWE 2K26 MyGM Companion.lnk"),Path.Combine(target,"MyGMCompanion.exe"));using var key=Registry.CurrentUser.CreateSubKey(@"Software\Microsoft\Windows\CurrentVersion\Uninstall\MyGMCompanion106");key.SetValue("DisplayName","WWE 2K26 MyGM Companion V11.4.1");key.SetValue("DisplayVersion","11.4.1");key.SetValue("DisplayIcon",Path.Combine(target,"MyGMCompanion.exe"));key.SetValue("InstallLocation",target);key.SetValue("UninstallString",'"'+Path.Combine(target,"uninstall.exe")+'"');key.SetValue("Publisher","MyGM Companion");}
 static void CreateShortcut(string shortcutPath,string exe){var shell=Activator.CreateInstance(Type.GetTypeFromProgID("WScript.Shell")!)!;dynamic link=shell.GetType().InvokeMember("CreateShortcut",System.Reflection.BindingFlags.InvokeMethod,null,shell,[shortcutPath])!;link.TargetPath=exe;link.WorkingDirectory=Path.GetDirectoryName(exe);link.Description="WWE 2K26 MyGM Companion V10.6";link.Save();}
}
