using System.Diagnostics;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text.Json;
using System.Windows.Forms;

internal static class Program {
 [STAThread]
 static void Main(string[] args){ApplicationConfiguration.Initialize();var options=Options.Parse(args);if(options is null){MessageBox.Show("Updater wurde ohne gültige Programmparameter gestartet.","MyGM Updater",MessageBoxButtons.OK,MessageBoxIcon.Error);return;}Application.Run(new UpdateForm(options));}
}
sealed record Options(string InstallDir,Version CurrentVersion,int AppPid){
 public static Options? Parse(string[] args){string? dir=null,version=null;int pid=0;for(var i=0;i<args.Length-1;i++){if(args[i]=="--install-dir")dir=args[++i];else if(args[i]=="--current-version")version=args[++i];else if(args[i]=="--app-pid")int.TryParse(args[++i],out pid);}return dir is not null&&Version.TryParse(version,out var v)?new(Path.GetFullPath(dir),v,pid):null;}
}
sealed record ReleaseAsset(string name,string browser_download_url,long size);
sealed record GithubRelease(string tag_name,string name,bool prerelease,bool draft,ReleaseAsset[] assets);
sealed class UpdateForm:Form {
 const string ApiUrl="https://api.github.com/repos/DeanRotations/WWE-2K26-MyGM-Companion/releases/latest";
 readonly Options options;readonly Label status=new(){AutoSize=false,Dock=DockStyle.Fill,TextAlign=System.Drawing.ContentAlignment.MiddleCenter};readonly ProgressBar progress=new(){Dock=DockStyle.Bottom,Height=18,Style=ProgressBarStyle.Marquee};readonly Button action=new(){Text="Prüfen",Dock=DockStyle.Bottom,Height=42};readonly CancellationTokenSource cts=new();GithubRelease? release;Version? latest;
 public UpdateForm(Options options){this.options=options;Text="MyGM Companion Updater";Width=520;Height=250;StartPosition=FormStartPosition.CenterScreen;FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;BackColor=System.Drawing.Color.FromArgb(13,15,21);ForeColor=System.Drawing.Color.White;status.Text="Suche nach Updates …";action.Visible=false;Controls.Add(status);Controls.Add(action);Controls.Add(progress);Shown+=async(_,_)=>await CheckAsync();FormClosing+=(_,_)=>cts.Cancel();action.Click+=async(_,_)=>await InstallAsync();}
 async Task CheckAsync(){try{using var http=Client();var json=await http.GetStringAsync(ApiUrl,cts.Token).WaitAsync(TimeSpan.FromSeconds(15),cts.Token);release=JsonSerializer.Deserialize<GithubRelease>(json,new JsonSerializerOptions{PropertyNameCaseInsensitive=true})??throw new InvalidDataException("Release-Antwort ist ungültig.");var tag=release.tag_name.TrimStart('v','V');if(!Version.TryParse(tag,out latest))throw new InvalidDataException("Release-Version ist ungültig.");progress.Visible=false;if(latest<=options.CurrentVersion){status.Text=$"Du verwendest bereits die aktuelle Version {options.CurrentVersion}.";return;}var zip=release.assets.FirstOrDefault(a=>a.name=="MyGMCompanion-update.zip");var sha=release.assets.FirstOrDefault(a=>a.name=="MyGMCompanion-update.zip.sha256");if(zip is null||sha is null)throw new InvalidDataException("Das Release enthält kein vollständiges Updatepaket.");status.Text=$"Version {latest} ist verfügbar.\n\n{release.name}";action.Text="Update herunterladen und installieren";action.Visible=true;}catch(OperationCanceledException){Close();}catch(Exception ex){progress.Visible=false;status.Text="Updateprüfung fehlgeschlagen:\n"+ex.Message;}}
 async Task InstallAsync(){if(release is null||latest is null)return;action.Enabled=false;progress.Visible=true;status.Text="Update wird heruntergeladen und geprüft …";var zipAsset=release.assets.First(a=>a.name=="MyGMCompanion-update.zip");var shaAsset=release.assets.First(a=>a.name=="MyGMCompanion-update.zip.sha256");var tempRoot=Path.Combine(Path.GetTempPath(),"MyGM-Update-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(tempRoot);try{using var http=Client();var zipPath=Path.Combine(tempRoot,"update.zip");await using(var input=await http.GetStreamAsync(zipAsset.browser_download_url,cts.Token).WaitAsync(TimeSpan.FromSeconds(60),cts.Token))await using(var output=File.Create(zipPath))await input.CopyToAsync(output,cts.Token);var expected=(await http.GetStringAsync(shaAsset.browser_download_url,cts.Token)).Split([' ','\r','\n'],StringSplitOptions.RemoveEmptyEntries)[0].Trim();await using(var hashStream=File.OpenRead(zipPath)){var actual=Convert.ToHexString(await SHA256.HashDataAsync(hashStream,cts.Token));if(!actual.Equals(expected,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("SHA-256-Prüfung fehlgeschlagen. Update wurde verworfen.");}
   status.Text="Update wird installiert …";if(options.AppPid>0){try{var app=Process.GetProcessById(options.AppPid);app.CloseMainWindow();if(!app.WaitForExit(8000))app.Kill(true);}catch{}}
   var extract=Path.Combine(tempRoot,"files");ZipFile.ExtractToDirectory(zipPath,extract);foreach(var source in Directory.EnumerateFiles(extract,"*",SearchOption.AllDirectories)){var relative=Path.GetRelativePath(extract,source);var top=relative.Split(Path.DirectorySeparatorChar)[0];if(new[]{"data","config","cache","logs"}.Contains(top,StringComparer.OrdinalIgnoreCase))continue;var destination=Path.GetFullPath(Path.Combine(options.InstallDir,relative));if(!destination.StartsWith(options.InstallDir,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("Ungültiger Updatepfad.");Directory.CreateDirectory(Path.GetDirectoryName(destination)!);File.Copy(source,destination,true);}File.WriteAllText(Path.Combine(options.InstallDir,"update-version.txt"),latest.ToString());Process.Start(new ProcessStartInfo(Path.Combine(options.InstallDir,"MyGMCompanion.exe")){UseShellExecute=true});status.Text="Update erfolgreich installiert.";progress.Visible=false;action.Visible=false;await Task.Delay(1200);Close();
  }catch(OperationCanceledException){Close();}catch(Exception ex){progress.Visible=false;action.Enabled=true;status.Text="Update fehlgeschlagen:\n"+ex.Message;}finally{try{Directory.Delete(tempRoot,true);}catch{}}}
 static HttpClient Client(){var http=new HttpClient();http.DefaultRequestHeaders.UserAgent.ParseAdd("MyGM-Companion-Updater/1.0");http.DefaultRequestHeaders.Accept.ParseAdd("application/vnd.github+json");return http;}
}
