<Project>
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Version>10.9.0</Version>
    <Company>MyGM Companion</Company>
    <Product>WWE 2K26 MyGM Companion</Product>
    <Copyright>Copyright © 2026</Copyright>
  </PropertyGroup>
</Project>

